"""WGL ctypes bindings generated from tools/gen_opengl/wgl.xml.

Generated by tools/gen_opengl/gen_wgl.py. Do not modify this file.
"""
from __future__ import annotations

from ctypes import CFUNCTYPE, POINTER, c_char_p, c_int, c_uint, c_void_p
from ctypes.wintypes import BOOL, COLORREF, DWORD, FLOAT, HANDLE, HDC, HENHMETAFILE, LPCSTR, UINT

from pyglet.graphics.api.gl.lib import link_WGL as _link_function
from pyglet.libs.win32.types import (
    HGPUNV,
    LAYERPLANEDESCRIPTOR,
    LPGLYPHMETRICSFLOAT,
    PGPU_DEVICE,
    PIXELFORMATDESCRIPTOR,
)

if not _link_function:
    raise ImportError("opengl32.dll is not available.")
# WGL type definitions
GLbitfield = c_uint
GLenum = c_uint
GLint = c_int
GLsizei = c_int
GLuint = c_uint
HGLRC = HANDLE
INT = c_int
PROC = CFUNCTYPE(c_int)
VOID = None

# WGL enumerant (token) definitions
ERROR_INCOMPATIBLE_AFFINITY_MASKS_NV = 0x20D0
ERROR_INVALID_PROFILE_ARB = 0x2096
ERROR_INVALID_VERSION_ARB = 0x2095
ERROR_MISSING_AFFINITY_MASK_NV = 0x20D1
WGL_ACCELERATION_ARB = 0x2003
WGL_ACCESS_READ_ONLY_NV = 0x00000000
WGL_ACCESS_READ_WRITE_NV = 0x00000001
WGL_ACCESS_WRITE_DISCARD_NV = 0x00000002
WGL_ACCUM_ALPHA_BITS_ARB = 0x2021
WGL_ACCUM_BITS_ARB = 0x201D
WGL_ACCUM_BLUE_BITS_ARB = 0x2020
WGL_ACCUM_GREEN_BITS_ARB = 0x201F
WGL_ACCUM_RED_BITS_ARB = 0x201E
WGL_ALPHA_BITS_ARB = 0x201B
WGL_ALPHA_SHIFT_ARB = 0x201C
WGL_AUX_BUFFERS_ARB = 0x2024
WGL_BLUE_BITS_ARB = 0x2019
WGL_BLUE_SHIFT_ARB = 0x201A
WGL_COLOR_BITS_ARB = 0x2014
WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB = 0x00000002
WGL_CONTEXT_CORE_PROFILE_BIT_ARB = 0x00000001
WGL_CONTEXT_DEBUG_BIT_ARB = 0x00000001
WGL_CONTEXT_ES2_PROFILE_BIT_EXT = 0x00000004
WGL_CONTEXT_FLAGS_ARB = 0x2094
WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB = 0x00000002
WGL_CONTEXT_LAYER_PLANE_ARB = 0x2093
WGL_CONTEXT_MAJOR_VERSION_ARB = 0x2091
WGL_CONTEXT_MINOR_VERSION_ARB = 0x2092
WGL_CONTEXT_PROFILE_MASK_ARB = 0x9126
WGL_DEPTH_BITS_ARB = 0x2022
WGL_DOUBLE_BUFFER_ARB = 0x2011
WGL_DRAW_TO_BITMAP_ARB = 0x2002
WGL_DRAW_TO_WINDOW_ARB = 0x2001
WGL_FONT_LINES = 0
WGL_FONT_POLYGONS = 1
WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB = 0x20A9
WGL_FULL_ACCELERATION_ARB = 0x2027
WGL_GENERIC_ACCELERATION_ARB = 0x2026
WGL_GPU_CLOCK_AMD = 0x21A4
WGL_GPU_FASTEST_TARGET_GPUS_AMD = 0x21A2
WGL_GPU_NUM_PIPES_AMD = 0x21A5
WGL_GPU_NUM_RB_AMD = 0x21A7
WGL_GPU_NUM_SIMD_AMD = 0x21A6
WGL_GPU_NUM_SPI_AMD = 0x21A8
WGL_GPU_OPENGL_VERSION_STRING_AMD = 0x1F02
WGL_GPU_RAM_AMD = 0x21A3
WGL_GPU_RENDERER_STRING_AMD = 0x1F01
WGL_GPU_VENDOR_AMD = 0x1F00
WGL_GREEN_BITS_ARB = 0x2017
WGL_GREEN_SHIFT_ARB = 0x2018
WGL_NEED_PALETTE_ARB = 0x2004
WGL_NEED_SYSTEM_PALETTE_ARB = 0x2005
WGL_NO_ACCELERATION_ARB = 0x2025
WGL_NUMBER_OVERLAYS_ARB = 0x2008
WGL_NUMBER_PIXEL_FORMATS_ARB = 0x2000
WGL_NUMBER_UNDERLAYS_ARB = 0x2009
WGL_PIXEL_TYPE_ARB = 0x2013
WGL_RED_BITS_ARB = 0x2015
WGL_RED_SHIFT_ARB = 0x2016
WGL_SAMPLES_ARB = 0x2042
WGL_SAMPLE_BUFFERS_ARB = 0x2041
WGL_SHARE_ACCUM_ARB = 0x200E
WGL_SHARE_DEPTH_ARB = 0x200C
WGL_SHARE_STENCIL_ARB = 0x200D
WGL_STENCIL_BITS_ARB = 0x2023
WGL_STEREO_ARB = 0x2012
WGL_SUPPORT_GDI_ARB = 0x200F
WGL_SUPPORT_OPENGL_ARB = 0x2010
WGL_SWAP_COPY_ARB = 0x2029
WGL_SWAP_EXCHANGE_ARB = 0x2028
WGL_SWAP_LAYER_BUFFERS_ARB = 0x2006
WGL_SWAP_MAIN_PLANE = 0x00000001
WGL_SWAP_METHOD_ARB = 0x2007
WGL_SWAP_OVERLAY1 = 0x00000002
WGL_SWAP_OVERLAY10 = 0x00000400
WGL_SWAP_OVERLAY11 = 0x00000800
WGL_SWAP_OVERLAY12 = 0x00001000
WGL_SWAP_OVERLAY13 = 0x00002000
WGL_SWAP_OVERLAY14 = 0x00004000
WGL_SWAP_OVERLAY15 = 0x00008000
WGL_SWAP_OVERLAY2 = 0x00000004
WGL_SWAP_OVERLAY3 = 0x00000008
WGL_SWAP_OVERLAY4 = 0x00000010
WGL_SWAP_OVERLAY5 = 0x00000020
WGL_SWAP_OVERLAY6 = 0x00000040
WGL_SWAP_OVERLAY7 = 0x00000080
WGL_SWAP_OVERLAY8 = 0x00000100
WGL_SWAP_OVERLAY9 = 0x00000200
WGL_SWAP_UNDEFINED_ARB = 0x202A
WGL_SWAP_UNDERLAY1 = 0x00010000
WGL_SWAP_UNDERLAY10 = 0x02000000
WGL_SWAP_UNDERLAY11 = 0x04000000
WGL_SWAP_UNDERLAY12 = 0x08000000
WGL_SWAP_UNDERLAY13 = 0x10000000
WGL_SWAP_UNDERLAY14 = 0x20000000
WGL_SWAP_UNDERLAY15 = 0x40000000
WGL_SWAP_UNDERLAY2 = 0x00020000
WGL_SWAP_UNDERLAY3 = 0x00040000
WGL_SWAP_UNDERLAY4 = 0x00080000
WGL_SWAP_UNDERLAY5 = 0x00100000
WGL_SWAP_UNDERLAY6 = 0x00200000
WGL_SWAP_UNDERLAY7 = 0x00400000
WGL_SWAP_UNDERLAY8 = 0x00800000
WGL_SWAP_UNDERLAY9 = 0x01000000
WGL_TRANSPARENT_ALPHA_VALUE_ARB = 0x203A
WGL_TRANSPARENT_ARB = 0x200A
WGL_TRANSPARENT_BLUE_VALUE_ARB = 0x2039
WGL_TRANSPARENT_GREEN_VALUE_ARB = 0x2038
WGL_TRANSPARENT_INDEX_VALUE_ARB = 0x203B
WGL_TRANSPARENT_RED_VALUE_ARB = 0x2037
WGL_TYPE_COLORINDEX_ARB = 0x202C
WGL_TYPE_RGBA_ARB = 0x202B

# WGL command definitions
wglBlitContextFramebufferAMD = _link_function('wglBlitContextFramebufferAMD', None, [HANDLE, c_int, c_int, c_int, c_int, c_int, c_int, c_int, c_int, c_uint, c_uint], 'WGL WGL_AMD_gpu_association')
wglChoosePixelFormatARB = _link_function('wglChoosePixelFormatARB', BOOL, [HDC, POINTER(c_int), POINTER(FLOAT), UINT, POINTER(c_int), POINTER(UINT)], 'WGL WGL_ARB_pixel_format')
wglCopyContext = _link_function('wglCopyContext', BOOL, [HANDLE, HANDLE, UINT], 'WGL 1.0')
wglCreateAffinityDCNV = _link_function('wglCreateAffinityDCNV', HDC, [POINTER(HGPUNV)], 'WGL WGL_NV_gpu_affinity')
wglCreateAssociatedContextAMD = _link_function('wglCreateAssociatedContextAMD', HANDLE, [UINT], 'WGL WGL_AMD_gpu_association')
wglCreateAssociatedContextAttribsAMD = _link_function('wglCreateAssociatedContextAttribsAMD', HANDLE, [UINT, HANDLE, POINTER(c_int)], 'WGL WGL_AMD_gpu_association')
wglCreateContext = _link_function('wglCreateContext', HANDLE, [HDC], 'WGL 1.0')
wglCreateContextAttribsARB = _link_function('wglCreateContextAttribsARB', HANDLE, [HDC, HANDLE, POINTER(c_int)], 'WGL WGL_ARB_create_context')
wglCreateLayerContext = _link_function('wglCreateLayerContext', HANDLE, [HDC, c_int], 'WGL 1.0')
wglDXCloseDeviceNV = _link_function('wglDXCloseDeviceNV', BOOL, [HANDLE], 'WGL WGL_NV_DX_interop')
wglDXLockObjectsNV = _link_function('wglDXLockObjectsNV', BOOL, [HANDLE, c_int, POINTER(HANDLE)], 'WGL WGL_NV_DX_interop')
wglDXObjectAccessNV = _link_function('wglDXObjectAccessNV', BOOL, [HANDLE, c_uint], 'WGL WGL_NV_DX_interop')
wglDXOpenDeviceNV = _link_function('wglDXOpenDeviceNV', HANDLE, [c_void_p], 'WGL WGL_NV_DX_interop')
wglDXRegisterObjectNV = _link_function('wglDXRegisterObjectNV', HANDLE, [HANDLE, c_void_p, c_uint, c_uint, c_uint], 'WGL WGL_NV_DX_interop')
wglDXSetResourceShareHandleNV = _link_function('wglDXSetResourceShareHandleNV', BOOL, [c_void_p, HANDLE], 'WGL WGL_NV_DX_interop')
wglDXUnlockObjectsNV = _link_function('wglDXUnlockObjectsNV', BOOL, [HANDLE, c_int, POINTER(HANDLE)], 'WGL WGL_NV_DX_interop')
wglDXUnregisterObjectNV = _link_function('wglDXUnregisterObjectNV', BOOL, [HANDLE, HANDLE], 'WGL WGL_NV_DX_interop')
wglDeleteAssociatedContextAMD = _link_function('wglDeleteAssociatedContextAMD', BOOL, [HANDLE], 'WGL WGL_AMD_gpu_association')
wglDeleteContext = _link_function('wglDeleteContext', BOOL, [HANDLE], 'WGL 1.0')
wglDeleteDCNV = _link_function('wglDeleteDCNV', BOOL, [HDC], 'WGL WGL_NV_gpu_affinity')
wglDescribeLayerPlane = _link_function('wglDescribeLayerPlane', BOOL, [HDC, c_int, c_int, UINT, POINTER(LAYERPLANEDESCRIPTOR)], 'WGL 1.0')
wglEnumGpuDevicesNV = _link_function('wglEnumGpuDevicesNV', BOOL, [HGPUNV, UINT, PGPU_DEVICE], 'WGL WGL_NV_gpu_affinity')
wglEnumGpusFromAffinityDCNV = _link_function('wglEnumGpusFromAffinityDCNV', BOOL, [HDC, UINT, POINTER(HGPUNV)], 'WGL WGL_NV_gpu_affinity')
wglEnumGpusNV = _link_function('wglEnumGpusNV', BOOL, [UINT, POINTER(HGPUNV)], 'WGL WGL_NV_gpu_affinity')
wglGetContextGPUIDAMD = _link_function('wglGetContextGPUIDAMD', UINT, [HANDLE], 'WGL WGL_AMD_gpu_association')
wglGetCurrentAssociatedContextAMD = _link_function('wglGetCurrentAssociatedContextAMD', HANDLE, [], 'WGL WGL_AMD_gpu_association')
wglGetCurrentContext = _link_function('wglGetCurrentContext', HANDLE, [], 'WGL 1.0')
wglGetCurrentDC = _link_function('wglGetCurrentDC', HDC, [], 'WGL 1.0')
wglGetExtensionsStringARB = _link_function('wglGetExtensionsStringARB', c_char_p, [HDC], 'WGL WGL_ARB_extensions_string')
wglGetExtensionsStringEXT = _link_function('wglGetExtensionsStringEXT', c_char_p, [], 'WGL WGL_EXT_extensions_string')
wglGetGPUIDsAMD = _link_function('wglGetGPUIDsAMD', UINT, [UINT, POINTER(UINT)], 'WGL WGL_AMD_gpu_association')
wglGetGPUInfoAMD = _link_function('wglGetGPUInfoAMD', c_int, [UINT, c_int, c_uint, UINT, c_void_p], 'WGL WGL_AMD_gpu_association')
wglGetLayerPaletteEntries = _link_function('wglGetLayerPaletteEntries', c_int, [HDC, c_int, c_int, c_int, POINTER(COLORREF)], 'WGL 1.0')
wglGetPixelFormatAttribfvARB = _link_function('wglGetPixelFormatAttribfvARB', BOOL, [HDC, c_int, c_int, UINT, POINTER(c_int), POINTER(FLOAT)], 'WGL WGL_ARB_pixel_format')
wglGetPixelFormatAttribivARB = _link_function('wglGetPixelFormatAttribivARB', BOOL, [HDC, c_int, c_int, UINT, POINTER(c_int), POINTER(c_int)], 'WGL WGL_ARB_pixel_format')
wglGetProcAddress = _link_function('wglGetProcAddress', CFUNCTYPE(c_int), [LPCSTR], 'WGL 1.0')
wglGetSwapIntervalEXT = _link_function('wglGetSwapIntervalEXT', c_int, [], 'WGL WGL_EXT_swap_control')
wglMakeAssociatedContextCurrentAMD = _link_function('wglMakeAssociatedContextCurrentAMD', BOOL, [HANDLE], 'WGL WGL_AMD_gpu_association')
wglMakeCurrent = _link_function('wglMakeCurrent', BOOL, [HDC, HANDLE], 'WGL 1.0')
wglRealizeLayerPalette = _link_function('wglRealizeLayerPalette', BOOL, [HDC, c_int, BOOL], 'WGL 1.0')
wglSetLayerPaletteEntries = _link_function('wglSetLayerPaletteEntries', c_int, [HDC, c_int, c_int, c_int, POINTER(COLORREF)], 'WGL 1.0')
wglShareLists = _link_function('wglShareLists', BOOL, [HANDLE, HANDLE], 'WGL 1.0')
wglSwapIntervalEXT = _link_function('wglSwapIntervalEXT', BOOL, [c_int], 'WGL WGL_EXT_swap_control')
wglSwapLayerBuffers = _link_function('wglSwapLayerBuffers', BOOL, [HDC, UINT], 'WGL 1.0')
wglUseFontBitmaps = _link_function('wglUseFontBitmaps', BOOL, [HDC, DWORD, DWORD, DWORD], 'WGL 1.0')
wglUseFontBitmapsA = _link_function('wglUseFontBitmapsA', BOOL, [HDC, DWORD, DWORD, DWORD], 'WGL 1.0')
wglUseFontBitmapsW = _link_function('wglUseFontBitmapsW', BOOL, [HDC, DWORD, DWORD, DWORD], 'WGL 1.0')
wglUseFontOutlines = _link_function('wglUseFontOutlines', BOOL, [HDC, DWORD, DWORD, DWORD, FLOAT, FLOAT, c_int, LPGLYPHMETRICSFLOAT], 'WGL 1.0')
wglUseFontOutlinesA = _link_function('wglUseFontOutlinesA', BOOL, [HDC, DWORD, DWORD, DWORD, FLOAT, FLOAT, c_int, LPGLYPHMETRICSFLOAT], 'WGL 1.0')
wglUseFontOutlinesW = _link_function('wglUseFontOutlinesW', BOOL, [HDC, DWORD, DWORD, DWORD, FLOAT, FLOAT, c_int, LPGLYPHMETRICSFLOAT], 'WGL 1.0')

class WGLFunctionsARB:
    def __init__(self) -> None:
        self.wglBlitContextFramebufferAMD = _link_function('wglBlitContextFramebufferAMD', None, [HANDLE, c_int, c_int, c_int, c_int, c_int, c_int, c_int, c_int, c_uint, c_uint], 'WGL WGL_AMD_gpu_association')
        self.wglChoosePixelFormatARB = _link_function('wglChoosePixelFormatARB', BOOL, [HDC, POINTER(c_int), POINTER(FLOAT), UINT, POINTER(c_int), POINTER(UINT)], 'WGL WGL_ARB_pixel_format')
        self.wglCopyContext = _link_function('wglCopyContext', BOOL, [HANDLE, HANDLE, UINT], 'WGL 1.0')
        self.wglCreateAffinityDCNV = _link_function('wglCreateAffinityDCNV', HDC, [POINTER(HGPUNV)], 'WGL WGL_NV_gpu_affinity')
        self.wglCreateAssociatedContextAMD = _link_function('wglCreateAssociatedContextAMD', HANDLE, [UINT], 'WGL WGL_AMD_gpu_association')
        self.wglCreateAssociatedContextAttribsAMD = _link_function('wglCreateAssociatedContextAttribsAMD', HANDLE, [UINT, HANDLE, POINTER(c_int)], 'WGL WGL_AMD_gpu_association')
        self.wglCreateContext = _link_function('wglCreateContext', HANDLE, [HDC], 'WGL 1.0')
        self.wglCreateContextAttribsARB = _link_function('wglCreateContextAttribsARB', HANDLE, [HDC, HANDLE, POINTER(c_int)], 'WGL WGL_ARB_create_context')
        self.wglCreateLayerContext = _link_function('wglCreateLayerContext', HANDLE, [HDC, c_int], 'WGL 1.0')
        self.wglDXCloseDeviceNV = _link_function('wglDXCloseDeviceNV', BOOL, [HANDLE], 'WGL WGL_NV_DX_interop')
        self.wglDXLockObjectsNV = _link_function('wglDXLockObjectsNV', BOOL, [HANDLE, c_int, POINTER(HANDLE)], 'WGL WGL_NV_DX_interop')
        self.wglDXObjectAccessNV = _link_function('wglDXObjectAccessNV', BOOL, [HANDLE, c_uint], 'WGL WGL_NV_DX_interop')
        self.wglDXOpenDeviceNV = _link_function('wglDXOpenDeviceNV', HANDLE, [c_void_p], 'WGL WGL_NV_DX_interop')
        self.wglDXRegisterObjectNV = _link_function('wglDXRegisterObjectNV', HANDLE, [HANDLE, c_void_p, c_uint, c_uint, c_uint], 'WGL WGL_NV_DX_interop')
        self.wglDXSetResourceShareHandleNV = _link_function('wglDXSetResourceShareHandleNV', BOOL, [c_void_p, HANDLE], 'WGL WGL_NV_DX_interop')
        self.wglDXUnlockObjectsNV = _link_function('wglDXUnlockObjectsNV', BOOL, [HANDLE, c_int, POINTER(HANDLE)], 'WGL WGL_NV_DX_interop')
        self.wglDXUnregisterObjectNV = _link_function('wglDXUnregisterObjectNV', BOOL, [HANDLE, HANDLE], 'WGL WGL_NV_DX_interop')
        self.wglDeleteAssociatedContextAMD = _link_function('wglDeleteAssociatedContextAMD', BOOL, [HANDLE], 'WGL WGL_AMD_gpu_association')
        self.wglDeleteContext = _link_function('wglDeleteContext', BOOL, [HANDLE], 'WGL 1.0')
        self.wglDeleteDCNV = _link_function('wglDeleteDCNV', BOOL, [HDC], 'WGL WGL_NV_gpu_affinity')
        self.wglDescribeLayerPlane = _link_function('wglDescribeLayerPlane', BOOL, [HDC, c_int, c_int, UINT, POINTER(LAYERPLANEDESCRIPTOR)], 'WGL 1.0')
        self.wglEnumGpuDevicesNV = _link_function('wglEnumGpuDevicesNV', BOOL, [HGPUNV, UINT, PGPU_DEVICE], 'WGL WGL_NV_gpu_affinity')
        self.wglEnumGpusFromAffinityDCNV = _link_function('wglEnumGpusFromAffinityDCNV', BOOL, [HDC, UINT, POINTER(HGPUNV)], 'WGL WGL_NV_gpu_affinity')
        self.wglEnumGpusNV = _link_function('wglEnumGpusNV', BOOL, [UINT, POINTER(HGPUNV)], 'WGL WGL_NV_gpu_affinity')
        self.wglGetContextGPUIDAMD = _link_function('wglGetContextGPUIDAMD', UINT, [HANDLE], 'WGL WGL_AMD_gpu_association')
        self.wglGetCurrentAssociatedContextAMD = _link_function('wglGetCurrentAssociatedContextAMD', HANDLE, [], 'WGL WGL_AMD_gpu_association')
        self.wglGetCurrentContext = _link_function('wglGetCurrentContext', HANDLE, [], 'WGL 1.0')
        self.wglGetCurrentDC = _link_function('wglGetCurrentDC', HDC, [], 'WGL 1.0')
        self.wglGetExtensionsStringARB = _link_function('wglGetExtensionsStringARB', c_char_p, [HDC], 'WGL WGL_ARB_extensions_string')
        self.wglGetExtensionsStringEXT = _link_function('wglGetExtensionsStringEXT', c_char_p, [], 'WGL WGL_EXT_extensions_string')
        self.wglGetGPUIDsAMD = _link_function('wglGetGPUIDsAMD', UINT, [UINT, POINTER(UINT)], 'WGL WGL_AMD_gpu_association')
        self.wglGetGPUInfoAMD = _link_function('wglGetGPUInfoAMD', c_int, [UINT, c_int, c_uint, UINT, c_void_p], 'WGL WGL_AMD_gpu_association')
        self.wglGetLayerPaletteEntries = _link_function('wglGetLayerPaletteEntries', c_int, [HDC, c_int, c_int, c_int, POINTER(COLORREF)], 'WGL 1.0')
        self.wglGetPixelFormatAttribfvARB = _link_function('wglGetPixelFormatAttribfvARB', BOOL, [HDC, c_int, c_int, UINT, POINTER(c_int), POINTER(FLOAT)], 'WGL WGL_ARB_pixel_format')
        self.wglGetPixelFormatAttribivARB = _link_function('wglGetPixelFormatAttribivARB', BOOL, [HDC, c_int, c_int, UINT, POINTER(c_int), POINTER(c_int)], 'WGL WGL_ARB_pixel_format')
        self.wglGetProcAddress = _link_function('wglGetProcAddress', CFUNCTYPE(c_int), [LPCSTR], 'WGL 1.0')
        self.wglGetSwapIntervalEXT = _link_function('wglGetSwapIntervalEXT', c_int, [], 'WGL WGL_EXT_swap_control')
        self.wglMakeAssociatedContextCurrentAMD = _link_function('wglMakeAssociatedContextCurrentAMD', BOOL, [HANDLE], 'WGL WGL_AMD_gpu_association')
        self.wglMakeCurrent = _link_function('wglMakeCurrent', BOOL, [HDC, HANDLE], 'WGL 1.0')
        self.wglRealizeLayerPalette = _link_function('wglRealizeLayerPalette', BOOL, [HDC, c_int, BOOL], 'WGL 1.0')
        self.wglSetLayerPaletteEntries = _link_function('wglSetLayerPaletteEntries', c_int, [HDC, c_int, c_int, c_int, POINTER(COLORREF)], 'WGL 1.0')
        self.wglShareLists = _link_function('wglShareLists', BOOL, [HANDLE, HANDLE], 'WGL 1.0')
        self.wglSwapIntervalEXT = _link_function('wglSwapIntervalEXT', BOOL, [c_int], 'WGL WGL_EXT_swap_control')
        self.wglSwapLayerBuffers = _link_function('wglSwapLayerBuffers', BOOL, [HDC, UINT], 'WGL 1.0')
        self.wglUseFontBitmaps = _link_function('wglUseFontBitmaps', BOOL, [HDC, DWORD, DWORD, DWORD], 'WGL 1.0')
        self.wglUseFontBitmapsA = _link_function('wglUseFontBitmapsA', BOOL, [HDC, DWORD, DWORD, DWORD], 'WGL 1.0')
        self.wglUseFontBitmapsW = _link_function('wglUseFontBitmapsW', BOOL, [HDC, DWORD, DWORD, DWORD], 'WGL 1.0')
        self.wglUseFontOutlines = _link_function('wglUseFontOutlines', BOOL, [HDC, DWORD, DWORD, DWORD, FLOAT, FLOAT, c_int, LPGLYPHMETRICSFLOAT], 'WGL 1.0')
        self.wglUseFontOutlinesA = _link_function('wglUseFontOutlinesA', BOOL, [HDC, DWORD, DWORD, DWORD, FLOAT, FLOAT, c_int, LPGLYPHMETRICSFLOAT], 'WGL 1.0')
        self.wglUseFontOutlinesW = _link_function('wglUseFontOutlinesW', BOOL, [HDC, DWORD, DWORD, DWORD, FLOAT, FLOAT, c_int, LPGLYPHMETRICSFLOAT], 'WGL 1.0')

class WGLFunctions(WGLFunctionsARB):
    def __init__(self) -> None:
        super().__init__()

__all__ = [
    'BOOL',
    'COLORREF',
    'DWORD',
    'FLOAT',
    'GLbitfield',
    'GLenum',
    'GLint',
    'GLsizei',
    'GLuint',
    'HANDLE',
    'HDC',
    'HENHMETAFILE',
    'HGPUNV',
    'HGLRC',
    'INT',
    'LAYERPLANEDESCRIPTOR',
    'LPCSTR',
    'LPGLYPHMETRICSFLOAT',
    'PIXELFORMATDESCRIPTOR',
    'PGPU_DEVICE',
    'PROC',
    'UINT',
    'VOID',
    'WGL_FONT_LINES',
    'WGL_FONT_POLYGONS',
    'WGL_SWAP_MAIN_PLANE',
    'WGL_SWAP_OVERLAY1',
    'WGL_SWAP_OVERLAY2',
    'WGL_SWAP_OVERLAY3',
    'WGL_SWAP_OVERLAY4',
    'WGL_SWAP_OVERLAY5',
    'WGL_SWAP_OVERLAY6',
    'WGL_SWAP_OVERLAY7',
    'WGL_SWAP_OVERLAY8',
    'WGL_SWAP_OVERLAY9',
    'WGL_SWAP_OVERLAY10',
    'WGL_SWAP_OVERLAY11',
    'WGL_SWAP_OVERLAY12',
    'WGL_SWAP_OVERLAY13',
    'WGL_SWAP_OVERLAY14',
    'WGL_SWAP_OVERLAY15',
    'WGL_SWAP_UNDERLAY1',
    'WGL_SWAP_UNDERLAY2',
    'WGL_SWAP_UNDERLAY3',
    'WGL_SWAP_UNDERLAY4',
    'WGL_SWAP_UNDERLAY5',
    'WGL_SWAP_UNDERLAY6',
    'WGL_SWAP_UNDERLAY7',
    'WGL_SWAP_UNDERLAY8',
    'WGL_SWAP_UNDERLAY9',
    'WGL_SWAP_UNDERLAY10',
    'WGL_SWAP_UNDERLAY11',
    'WGL_SWAP_UNDERLAY12',
    'WGL_SWAP_UNDERLAY13',
    'WGL_SWAP_UNDERLAY14',
    'WGL_SWAP_UNDERLAY15',
    'WGL_CONTEXT_DEBUG_BIT_ARB',
    'WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB',
    'WGL_CONTEXT_MAJOR_VERSION_ARB',
    'WGL_CONTEXT_MINOR_VERSION_ARB',
    'WGL_CONTEXT_LAYER_PLANE_ARB',
    'WGL_CONTEXT_FLAGS_ARB',
    'ERROR_INVALID_VERSION_ARB',
    'WGL_CONTEXT_PROFILE_MASK_ARB',
    'WGL_CONTEXT_CORE_PROFILE_BIT_ARB',
    'WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB',
    'ERROR_INVALID_PROFILE_ARB',
    'WGL_NUMBER_PIXEL_FORMATS_ARB',
    'WGL_DRAW_TO_WINDOW_ARB',
    'WGL_DRAW_TO_BITMAP_ARB',
    'WGL_ACCELERATION_ARB',
    'WGL_NEED_PALETTE_ARB',
    'WGL_NEED_SYSTEM_PALETTE_ARB',
    'WGL_SWAP_LAYER_BUFFERS_ARB',
    'WGL_SWAP_METHOD_ARB',
    'WGL_NUMBER_OVERLAYS_ARB',
    'WGL_NUMBER_UNDERLAYS_ARB',
    'WGL_TRANSPARENT_ARB',
    'WGL_TRANSPARENT_RED_VALUE_ARB',
    'WGL_TRANSPARENT_GREEN_VALUE_ARB',
    'WGL_TRANSPARENT_BLUE_VALUE_ARB',
    'WGL_TRANSPARENT_ALPHA_VALUE_ARB',
    'WGL_TRANSPARENT_INDEX_VALUE_ARB',
    'WGL_SHARE_DEPTH_ARB',
    'WGL_SHARE_STENCIL_ARB',
    'WGL_SHARE_ACCUM_ARB',
    'WGL_SUPPORT_GDI_ARB',
    'WGL_SUPPORT_OPENGL_ARB',
    'WGL_DOUBLE_BUFFER_ARB',
    'WGL_STEREO_ARB',
    'WGL_PIXEL_TYPE_ARB',
    'WGL_COLOR_BITS_ARB',
    'WGL_RED_BITS_ARB',
    'WGL_RED_SHIFT_ARB',
    'WGL_GREEN_BITS_ARB',
    'WGL_GREEN_SHIFT_ARB',
    'WGL_BLUE_BITS_ARB',
    'WGL_BLUE_SHIFT_ARB',
    'WGL_ALPHA_BITS_ARB',
    'WGL_ALPHA_SHIFT_ARB',
    'WGL_ACCUM_BITS_ARB',
    'WGL_ACCUM_RED_BITS_ARB',
    'WGL_ACCUM_GREEN_BITS_ARB',
    'WGL_ACCUM_BLUE_BITS_ARB',
    'WGL_ACCUM_ALPHA_BITS_ARB',
    'WGL_DEPTH_BITS_ARB',
    'WGL_STENCIL_BITS_ARB',
    'WGL_AUX_BUFFERS_ARB',
    'WGL_NO_ACCELERATION_ARB',
    'WGL_GENERIC_ACCELERATION_ARB',
    'WGL_FULL_ACCELERATION_ARB',
    'WGL_SWAP_EXCHANGE_ARB',
    'WGL_SWAP_COPY_ARB',
    'WGL_SWAP_UNDEFINED_ARB',
    'WGL_TYPE_RGBA_ARB',
    'WGL_TYPE_COLORINDEX_ARB',
    'WGL_CONTEXT_ES2_PROFILE_BIT_EXT',
    'WGL_SAMPLE_BUFFERS_ARB',
    'WGL_SAMPLES_ARB',
    'WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB',
    'WGL_ACCESS_READ_ONLY_NV',
    'WGL_ACCESS_READ_WRITE_NV',
    'WGL_ACCESS_WRITE_DISCARD_NV',
    'ERROR_INCOMPATIBLE_AFFINITY_MASKS_NV',
    'ERROR_MISSING_AFFINITY_MASK_NV',
    'WGL_GPU_VENDOR_AMD',
    'WGL_GPU_RENDERER_STRING_AMD',
    'WGL_GPU_OPENGL_VERSION_STRING_AMD',
    'WGL_GPU_FASTEST_TARGET_GPUS_AMD',
    'WGL_GPU_RAM_AMD',
    'WGL_GPU_CLOCK_AMD',
    'WGL_GPU_NUM_PIPES_AMD',
    'WGL_GPU_NUM_SIMD_AMD',
    'WGL_GPU_NUM_RB_AMD',
    'WGL_GPU_NUM_SPI_AMD',
    'wglBlitContextFramebufferAMD',
    'wglChoosePixelFormatARB',
    'wglCopyContext',
    'wglCreateAffinityDCNV',
    'wglCreateAssociatedContextAMD',
    'wglCreateAssociatedContextAttribsAMD',
    'wglCreateContext',
    'wglCreateContextAttribsARB',
    'wglCreateLayerContext',
    'wglDXCloseDeviceNV',
    'wglDXLockObjectsNV',
    'wglDXObjectAccessNV',
    'wglDXOpenDeviceNV',
    'wglDXRegisterObjectNV',
    'wglDXSetResourceShareHandleNV',
    'wglDXUnlockObjectsNV',
    'wglDXUnregisterObjectNV',
    'wglDeleteAssociatedContextAMD',
    'wglDeleteContext',
    'wglDeleteDCNV',
    'wglDescribeLayerPlane',
    'wglEnumGpuDevicesNV',
    'wglEnumGpusFromAffinityDCNV',
    'wglEnumGpusNV',
    'wglGetContextGPUIDAMD',
    'wglGetCurrentAssociatedContextAMD',
    'wglGetCurrentContext',
    'wglGetCurrentDC',
    'wglGetExtensionsStringARB',
    'wglGetExtensionsStringEXT',
    'wglGetGPUIDsAMD',
    'wglGetGPUInfoAMD',
    'wglGetLayerPaletteEntries',
    'wglGetPixelFormatAttribfvARB',
    'wglGetPixelFormatAttribivARB',
    'wglGetProcAddress',
    'wglGetSwapIntervalEXT',
    'wglMakeAssociatedContextCurrentAMD',
    'wglMakeCurrent',
    'wglRealizeLayerPalette',
    'wglSetLayerPaletteEntries',
    'wglShareLists',
    'wglSwapIntervalEXT',
    'wglSwapLayerBuffers',
    'wglUseFontBitmaps',
    'wglUseFontBitmapsA',
    'wglUseFontBitmapsW',
    'wglUseFontOutlines',
    'wglUseFontOutlinesA',
    'wglUseFontOutlinesW',
    'WGLFunctionsARB',
    'WGLFunctions',
]
