# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

formats:
  - epub
  - htmlzip

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: doc/requirements.txt
