# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

formats:
  - epub
  - htmlzip

python:
  version: "3.8"
  install:
    - requirements: doc/requirements.txt
