
"""ARB_vertex_program
http://oss.sgi.com/projects/ogl-sample/registry/ARB/vertex_program.txt
"""

import ctypes as _ctypes
from pyglet.GL import get_function as _get_function
from pyglet.GL import c_ptrdiff_t as _c_ptrdiff_t
GL_COLOR_SUM_ARB = 0x8458
GL_VERTEX_PROGRAM_ARB = 0x8620
GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB = 0x8622
GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB = 0x8623
GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB = 0x8624
GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB = 0x8625
GL_CURRENT_VERTEX_ATTRIB_ARB = 0x8626
GL_PROGRAM_LENGTH_ARB = 0x8627
GL_PROGRAM_STRING_ARB = 0x8628
GL_MAX_PROGRAM_MATRIX_STACK_DEPTH_ARB = 0x862E
GL_MAX_PROGRAM_MATRICES_ARB = 0x862F
GL_CURRENT_MATRIX_STACK_DEPTH_ARB = 0x8640
GL_CURRENT_MATRIX_ARB = 0x8641
GL_VERTEX_PROGRAM_POINT_SIZE_ARB = 0x8642
GL_VERTEX_PROGRAM_TWO_SIDE_ARB = 0x8643
GL_VERTEX_ATTRIB_ARRAY_POINTER_ARB = 0x8645
GL_PROGRAM_ERROR_POSITION_ARB = 0x864B
GL_PROGRAM_BINDING_ARB = 0x8677
GL_MAX_VERTEX_ATTRIBS_ARB = 0x8869
GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB = 0x886A
GL_PROGRAM_ERROR_STRING_ARB = 0x8874
GL_PROGRAM_FORMAT_ASCII_ARB = 0x8875
GL_PROGRAM_FORMAT_ARB = 0x8876
GL_PROGRAM_INSTRUCTIONS_ARB = 0x88A0
GL_MAX_PROGRAM_INSTRUCTIONS_ARB = 0x88A1
GL_PROGRAM_NATIVE_INSTRUCTIONS_ARB = 0x88A2
GL_MAX_PROGRAM_NATIVE_INSTRUCTIONS_ARB = 0x88A3
GL_PROGRAM_TEMPORARIES_ARB = 0x88A4
GL_MAX_PROGRAM_TEMPORARIES_ARB = 0x88A5
GL_PROGRAM_NATIVE_TEMPORARIES_ARB = 0x88A6
GL_MAX_PROGRAM_NATIVE_TEMPORARIES_ARB = 0x88A7
GL_PROGRAM_PARAMETERS_ARB = 0x88A8
GL_MAX_PROGRAM_PARAMETERS_ARB = 0x88A9
GL_PROGRAM_NATIVE_PARAMETERS_ARB = 0x88AA
GL_MAX_PROGRAM_NATIVE_PARAMETERS_ARB = 0x88AB
GL_PROGRAM_ATTRIBS_ARB = 0x88AC
GL_MAX_PROGRAM_ATTRIBS_ARB = 0x88AD
GL_PROGRAM_NATIVE_ATTRIBS_ARB = 0x88AE
GL_MAX_PROGRAM_NATIVE_ATTRIBS_ARB = 0x88AF
GL_PROGRAM_ADDRESS_REGISTERS_ARB = 0x88B0
GL_MAX_PROGRAM_ADDRESS_REGISTERS_ARB = 0x88B1
GL_PROGRAM_NATIVE_ADDRESS_REGISTERS_ARB = 0x88B2
GL_MAX_PROGRAM_NATIVE_ADDRESS_REGISTERS_ARB = 0x88B3
GL_MAX_PROGRAM_LOCAL_PARAMETERS_ARB = 0x88B4
GL_MAX_PROGRAM_ENV_PARAMETERS_ARB = 0x88B5
GL_PROGRAM_UNDER_NATIVE_LIMITS_ARB = 0x88B6
GL_TRANSPOSE_CURRENT_MATRIX_ARB = 0x88B7
GL_MATRIX0_ARB = 0x88C0
GL_MATRIX1_ARB = 0x88C1
GL_MATRIX2_ARB = 0x88C2
GL_MATRIX3_ARB = 0x88C3
GL_MATRIX4_ARB = 0x88C4
GL_MATRIX5_ARB = 0x88C5
GL_MATRIX6_ARB = 0x88C6
GL_MATRIX7_ARB = 0x88C7
GL_MATRIX8_ARB = 0x88C8
GL_MATRIX9_ARB = 0x88C9
GL_MATRIX10_ARB = 0x88CA
GL_MATRIX11_ARB = 0x88CB
GL_MATRIX12_ARB = 0x88CC
GL_MATRIX13_ARB = 0x88CD
GL_MATRIX14_ARB = 0x88CE
GL_MATRIX15_ARB = 0x88CF
GL_MATRIX16_ARB = 0x88D0
GL_MATRIX17_ARB = 0x88D1
GL_MATRIX18_ARB = 0x88D2
GL_MATRIX19_ARB = 0x88D3
GL_MATRIX20_ARB = 0x88D4
GL_MATRIX21_ARB = 0x88D5
GL_MATRIX22_ARB = 0x88D6
GL_MATRIX23_ARB = 0x88D7
GL_MATRIX24_ARB = 0x88D8
GL_MATRIX25_ARB = 0x88D9
GL_MATRIX26_ARB = 0x88DA
GL_MATRIX27_ARB = 0x88DB
GL_MATRIX28_ARB = 0x88DC
GL_MATRIX29_ARB = 0x88DD
GL_MATRIX30_ARB = 0x88DE
GL_MATRIX31_ARB = 0x88DF
glBindProgramARB = _get_function('glBindProgramARB', [_ctypes.c_uint, _ctypes.c_uint], None)
glDeleteProgramsARB = _get_function('glDeleteProgramsARB', [_ctypes.c_int, _ctypes.POINTER(_ctypes.c_uint)], None)
glDisableVertexAttribArrayARB = _get_function('glDisableVertexAttribArrayARB', [_ctypes.c_uint], None)
glEnableVertexAttribArrayARB = _get_function('glEnableVertexAttribArrayARB', [_ctypes.c_uint], None)
glGenProgramsARB = _get_function('glGenProgramsARB', [_ctypes.c_int, _ctypes.POINTER(_ctypes.c_uint)], None)
glGetProgramEnvParameterdvARB = _get_function('glGetProgramEnvParameterdvARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glGetProgramEnvParameterfvARB = _get_function('glGetProgramEnvParameterfvARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glGetProgramLocalParameterdvARB = _get_function('glGetProgramLocalParameterdvARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glGetProgramLocalParameterfvARB = _get_function('glGetProgramLocalParameterfvARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glGetProgramStringARB = _get_function('glGetProgramStringARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_void_p], None)
glGetProgramivARB = _get_function('glGetProgramivARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glGetVertexAttribPointervARB = _get_function('glGetVertexAttribPointervARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_void_p)], None)
glGetVertexAttribdvARB = _get_function('glGetVertexAttribdvARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glGetVertexAttribfvARB = _get_function('glGetVertexAttribfvARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glGetVertexAttribivARB = _get_function('glGetVertexAttribivARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glIsProgramARB = _get_function('glIsProgramARB', [_ctypes.c_uint], _ctypes.c_ubyte)
glProgramEnvParameter4dARB = _get_function('glProgramEnvParameter4dARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double], None)
glProgramEnvParameter4dvARB = _get_function('glProgramEnvParameter4dvARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glProgramEnvParameter4fARB = _get_function('glProgramEnvParameter4fARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glProgramEnvParameter4fvARB = _get_function('glProgramEnvParameter4fvARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glProgramLocalParameter4dARB = _get_function('glProgramLocalParameter4dARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double], None)
glProgramLocalParameter4dvARB = _get_function('glProgramLocalParameter4dvARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glProgramLocalParameter4fARB = _get_function('glProgramLocalParameter4fARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glProgramLocalParameter4fvARB = _get_function('glProgramLocalParameter4fvARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glProgramStringARB = _get_function('glProgramStringARB', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_void_p], None)
glVertexAttrib1dARB = _get_function('glVertexAttrib1dARB', [_ctypes.c_uint, _ctypes.c_double], None)
glVertexAttrib1dvARB = _get_function('glVertexAttrib1dvARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttrib1fARB = _get_function('glVertexAttrib1fARB', [_ctypes.c_uint, _ctypes.c_float], None)
glVertexAttrib1fvARB = _get_function('glVertexAttrib1fvARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttrib1sARB = _get_function('glVertexAttrib1sARB', [_ctypes.c_uint, _ctypes.c_short], None)
glVertexAttrib1svARB = _get_function('glVertexAttrib1svARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttrib2dARB = _get_function('glVertexAttrib2dARB', [_ctypes.c_uint, _ctypes.c_double, _ctypes.c_double], None)
glVertexAttrib2dvARB = _get_function('glVertexAttrib2dvARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttrib2fARB = _get_function('glVertexAttrib2fARB', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float], None)
glVertexAttrib2fvARB = _get_function('glVertexAttrib2fvARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttrib2sARB = _get_function('glVertexAttrib2sARB', [_ctypes.c_uint, _ctypes.c_short, _ctypes.c_short], None)
glVertexAttrib2svARB = _get_function('glVertexAttrib2svARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttrib3dARB = _get_function('glVertexAttrib3dARB', [_ctypes.c_uint, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double], None)
glVertexAttrib3dvARB = _get_function('glVertexAttrib3dvARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttrib3fARB = _get_function('glVertexAttrib3fARB', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glVertexAttrib3fvARB = _get_function('glVertexAttrib3fvARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttrib3sARB = _get_function('glVertexAttrib3sARB', [_ctypes.c_uint, _ctypes.c_short, _ctypes.c_short, _ctypes.c_short], None)
glVertexAttrib3svARB = _get_function('glVertexAttrib3svARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttrib4NbvARB = _get_function('glVertexAttrib4NbvARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_byte)], None)
glVertexAttrib4NivARB = _get_function('glVertexAttrib4NivARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glVertexAttrib4NsvARB = _get_function('glVertexAttrib4NsvARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttrib4NubARB = _get_function('glVertexAttrib4NubARB', [_ctypes.c_uint, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_ubyte], None)
glVertexAttrib4NubvARB = _get_function('glVertexAttrib4NubvARB', [_ctypes.c_uint, _ctypes.c_char_p], None)
glVertexAttrib4NuivARB = _get_function('glVertexAttrib4NuivARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_uint)], None)
glVertexAttrib4NusvARB = _get_function('glVertexAttrib4NusvARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_ushort)], None)
glVertexAttrib4bvARB = _get_function('glVertexAttrib4bvARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_byte)], None)
glVertexAttrib4dARB = _get_function('glVertexAttrib4dARB', [_ctypes.c_uint, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double], None)
glVertexAttrib4dvARB = _get_function('glVertexAttrib4dvARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttrib4fARB = _get_function('glVertexAttrib4fARB', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glVertexAttrib4fvARB = _get_function('glVertexAttrib4fvARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttrib4ivARB = _get_function('glVertexAttrib4ivARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glVertexAttrib4sARB = _get_function('glVertexAttrib4sARB', [_ctypes.c_uint, _ctypes.c_short, _ctypes.c_short, _ctypes.c_short, _ctypes.c_short], None)
glVertexAttrib4svARB = _get_function('glVertexAttrib4svARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttrib4ubvARB = _get_function('glVertexAttrib4ubvARB', [_ctypes.c_uint, _ctypes.c_char_p], None)
glVertexAttrib4uivARB = _get_function('glVertexAttrib4uivARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_uint)], None)
glVertexAttrib4usvARB = _get_function('glVertexAttrib4usvARB', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_ushort)], None)
glVertexAttribPointerARB = _get_function('glVertexAttribPointerARB', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_ubyte, _ctypes.c_int, _ctypes.c_void_p], None)
