
"""ARB_imaging
GL_CONSTANT_COLOR 0x8001
"""

import ctypes as _ctypes
from pyglet.GL import get_function as _get_function
from pyglet.GL import c_ptrdiff_t as _c_ptrdiff_t
GL_ONE_MINUS_CONSTANT_COLOR = 0x8002
GL_CONSTANT_ALPHA = 0x8003
GL_ONE_MINUS_CONSTANT_ALPHA = 0x8004
GL_BLEND_COLOR = 0x8005
GL_FUNC_ADD = 0x8006
GL_MIN = 0x8007
GL_MAX = 0x8008
GL_BLEND_EQUATION = 0x8009
GL_FUNC_SUBTRACT = 0x800A
GL_FUNC_REVERSE_SUBTRACT = 0x800B
GL_CONVOLUTION_1D = 0x8010
GL_CONVOLUTION_2D = 0x8011
GL_SEPARABLE_2D = 0x8012
GL_CONVOLUTION_BORDER_MODE = 0x8013
GL_CONVOLUTION_FILTER_SCALE = 0x8014
GL_CONVOLUTION_FILTER_BIAS = 0x8015
GL_REDUCE = 0x8016
GL_CONVOLUTION_FORMAT = 0x8017
GL_CONVOLUTION_WIDTH = 0x8018
GL_CONVOLUTION_HEIGHT = 0x8019
GL_MAX_CONVOLUTION_WIDTH = 0x801A
GL_MAX_CONVOLUTION_HEIGHT = 0x801B
GL_POST_CONVOLUTION_RED_SCALE = 0x801C
GL_POST_CONVOLUTION_GREEN_SCALE = 0x801D
GL_POST_CONVOLUTION_BLUE_SCALE = 0x801E
GL_POST_CONVOLUTION_ALPHA_SCALE = 0x801F
GL_POST_CONVOLUTION_RED_BIAS = 0x8020
GL_POST_CONVOLUTION_GREEN_BIAS = 0x8021
GL_POST_CONVOLUTION_BLUE_BIAS = 0x8022
GL_POST_CONVOLUTION_ALPHA_BIAS = 0x8023
GL_HISTOGRAM = 0x8024
GL_PROXY_HISTOGRAM = 0x8025
GL_HISTOGRAM_WIDTH = 0x8026
GL_HISTOGRAM_FORMAT = 0x8027
GL_HISTOGRAM_RED_SIZE = 0x8028
GL_HISTOGRAM_GREEN_SIZE = 0x8029
GL_HISTOGRAM_BLUE_SIZE = 0x802A
GL_HISTOGRAM_ALPHA_SIZE = 0x802B
GL_HISTOGRAM_LUMINANCE_SIZE = 0x802C
GL_HISTOGRAM_SINK = 0x802D
GL_MINMAX = 0x802E
GL_MINMAX_FORMAT = 0x802F
GL_MINMAX_SINK = 0x8030
GL_TABLE_TOO_LARGE = 0x8031
GL_COLOR_MATRIX = 0x80B1
GL_COLOR_MATRIX_STACK_DEPTH = 0x80B2
GL_MAX_COLOR_MATRIX_STACK_DEPTH = 0x80B3
GL_POST_COLOR_MATRIX_RED_SCALE = 0x80B4
GL_POST_COLOR_MATRIX_GREEN_SCALE = 0x80B5
GL_POST_COLOR_MATRIX_BLUE_SCALE = 0x80B6
GL_POST_COLOR_MATRIX_ALPHA_SCALE = 0x80B7
GL_POST_COLOR_MATRIX_RED_BIAS = 0x80B8
GL_POST_COLOR_MATRIX_GREEN_BIAS = 0x80B9
GL_POST_COLOR_MATRIX_BLUE_BIAS = 0x80BA
GL_POST_COLOR_MATRIX_ALPHA_BIAS = 0x80BB
GL_COLOR_TABLE = 0x80D0
GL_POST_CONVOLUTION_COLOR_TABLE = 0x80D1
GL_POST_COLOR_MATRIX_COLOR_TABLE = 0x80D2
GL_PROXY_COLOR_TABLE = 0x80D3
GL_PROXY_POST_CONVOLUTION_COLOR_TABLE = 0x80D4
GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE = 0x80D5
GL_COLOR_TABLE_SCALE = 0x80D6
GL_COLOR_TABLE_BIAS = 0x80D7
GL_COLOR_TABLE_FORMAT = 0x80D8
GL_COLOR_TABLE_WIDTH = 0x80D9
GL_COLOR_TABLE_RED_SIZE = 0x80DA
GL_COLOR_TABLE_GREEN_SIZE = 0x80DB
GL_COLOR_TABLE_BLUE_SIZE = 0x80DC
GL_COLOR_TABLE_ALPHA_SIZE = 0x80DD
GL_COLOR_TABLE_LUMINANCE_SIZE = 0x80DE
GL_COLOR_TABLE_INTENSITY_SIZE = 0x80DF
GL_IGNORE_BORDER = 0x8150
GL_CONSTANT_BORDER = 0x8151
GL_WRAP_BORDER = 0x8152
GL_REPLICATE_BORDER = 0x8153
GL_CONVOLUTION_BORDER_COLOR = 0x8154
glColorTable = _get_function('glColorTable', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_uint, _ctypes.c_void_p], None)
glColorSubTable = _get_function('glColorSubTable', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_uint, _ctypes.c_void_p], None)
glColorTableParameteriv = _get_function('glColorTableParameteriv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glColorTableParameterfv = _get_function('glColorTableParameterfv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glCopyColorSubTable = _get_function('glCopyColorSubTable', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int], None)
glCopyColorTable = _get_function('glCopyColorTable', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int], None)
glGetColorTable = _get_function('glGetColorTable', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_uint, _ctypes.c_void_p], None)
glGetColorTableParameterfv = _get_function('glGetColorTableParameterfv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glGetColorTableParameteriv = _get_function('glGetColorTableParameteriv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glHistogram = _get_function('glHistogram', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_ubyte], None)
glResetHistogram = _get_function('glResetHistogram', [_ctypes.c_uint], None)
glGetHistogram = _get_function('glGetHistogram', [_ctypes.c_uint, _ctypes.c_ubyte, _ctypes.c_uint, _ctypes.c_uint, _ctypes.c_void_p], None)
glGetHistogramParameterfv = _get_function('glGetHistogramParameterfv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glGetHistogramParameteriv = _get_function('glGetHistogramParameteriv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glMinmax = _get_function('glMinmax', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_ubyte], None)
glResetMinmax = _get_function('glResetMinmax', [_ctypes.c_uint], None)
glGetMinmaxParameterfv = _get_function('glGetMinmaxParameterfv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glGetMinmaxParameteriv = _get_function('glGetMinmaxParameteriv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glConvolutionFilter1D = _get_function('glConvolutionFilter1D', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_uint, _ctypes.c_void_p], None)
glConvolutionFilter2D = _get_function('glConvolutionFilter2D', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_uint, _ctypes.c_void_p], None)
glConvolutionParameterf = _get_function('glConvolutionParameterf', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_float], None)
glConvolutionParameterfv = _get_function('glConvolutionParameterfv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glConvolutionParameteri = _get_function('glConvolutionParameteri', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_int], None)
glConvolutionParameteriv = _get_function('glConvolutionParameteriv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glCopyConvolutionFilter1D = _get_function('glCopyConvolutionFilter1D', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int], None)
glCopyConvolutionFilter2D = _get_function('glCopyConvolutionFilter2D', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int], None)
glGetConvolutionFilter = _get_function('glGetConvolutionFilter', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_uint, _ctypes.c_void_p], None)
glGetConvolutionParameterfv = _get_function('glGetConvolutionParameterfv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glGetConvolutionParameteriv = _get_function('glGetConvolutionParameteriv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glSeparableFilter2D = _get_function('glSeparableFilter2D', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_uint, _ctypes.c_void_p, _ctypes.c_void_p], None)
glGetSeparableFilter = _get_function('glGetSeparableFilter', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_uint, _ctypes.c_void_p, _ctypes.c_void_p, _ctypes.c_void_p], None)
glGetMinmax = _get_function('glGetMinmax', [_ctypes.c_uint, _ctypes.c_ubyte, _ctypes.c_uint, _ctypes.c_uint, _ctypes.c_void_p], None)
