
"""NV_vertex_program
http://oss.sgi.com/projects/ogl-sample/registry/NV/vertex_program.txt
"""

import ctypes as _ctypes
from pyglet.GL import get_function as _get_function
from pyglet.GL import c_ptrdiff_t as _c_ptrdiff_t
GL_VERTEX_PROGRAM_NV = 0x8620
GL_VERTEX_STATE_PROGRAM_NV = 0x8621
GL_ATTRIB_ARRAY_SIZE_NV = 0x8623
GL_ATTRIB_ARRAY_STRIDE_NV = 0x8624
GL_ATTRIB_ARRAY_TYPE_NV = 0x8625
GL_CURRENT_ATTRIB_NV = 0x8626
GL_PROGRAM_LENGTH_NV = 0x8627
GL_PROGRAM_STRING_NV = 0x8628
GL_MODELVIEW_PROJECTION_NV = 0x8629
GL_IDENTITY_NV = 0x862A
GL_INVERSE_NV = 0x862B
GL_TRANSPOSE_NV = 0x862C
GL_INVERSE_TRANSPOSE_NV = 0x862D
GL_MAX_TRACK_MATRIX_STACK_DEPTH_NV = 0x862E
GL_MAX_TRACK_MATRICES_NV = 0x862F
GL_MATRIX0_NV = 0x8630
GL_MATRIX1_NV = 0x8631
GL_MATRIX2_NV = 0x8632
GL_MATRIX3_NV = 0x8633
GL_MATRIX4_NV = 0x8634
GL_MATRIX5_NV = 0x8635
GL_MATRIX6_NV = 0x8636
GL_MATRIX7_NV = 0x8637
GL_CURRENT_MATRIX_STACK_DEPTH_NV = 0x8640
GL_CURRENT_MATRIX_NV = 0x8641
GL_VERTEX_PROGRAM_POINT_SIZE_NV = 0x8642
GL_VERTEX_PROGRAM_TWO_SIDE_NV = 0x8643
GL_PROGRAM_PARAMETER_NV = 0x8644
GL_ATTRIB_ARRAY_POINTER_NV = 0x8645
GL_PROGRAM_TARGET_NV = 0x8646
GL_PROGRAM_RESIDENT_NV = 0x8647
GL_TRACK_MATRIX_NV = 0x8648
GL_TRACK_MATRIX_TRANSFORM_NV = 0x8649
GL_VERTEX_PROGRAM_BINDING_NV = 0x864A
GL_PROGRAM_ERROR_POSITION_NV = 0x864B
GL_VERTEX_ATTRIB_ARRAY0_NV = 0x8650
GL_VERTEX_ATTRIB_ARRAY1_NV = 0x8651
GL_VERTEX_ATTRIB_ARRAY2_NV = 0x8652
GL_VERTEX_ATTRIB_ARRAY3_NV = 0x8653
GL_VERTEX_ATTRIB_ARRAY4_NV = 0x8654
GL_VERTEX_ATTRIB_ARRAY5_NV = 0x8655
GL_VERTEX_ATTRIB_ARRAY6_NV = 0x8656
GL_VERTEX_ATTRIB_ARRAY7_NV = 0x8657
GL_VERTEX_ATTRIB_ARRAY8_NV = 0x8658
GL_VERTEX_ATTRIB_ARRAY9_NV = 0x8659
GL_VERTEX_ATTRIB_ARRAY10_NV = 0x865A
GL_VERTEX_ATTRIB_ARRAY11_NV = 0x865B
GL_VERTEX_ATTRIB_ARRAY12_NV = 0x865C
GL_VERTEX_ATTRIB_ARRAY13_NV = 0x865D
GL_VERTEX_ATTRIB_ARRAY14_NV = 0x865E
GL_VERTEX_ATTRIB_ARRAY15_NV = 0x865F
GL_MAP1_VERTEX_ATTRIB0_4_NV = 0x8660
GL_MAP1_VERTEX_ATTRIB1_4_NV = 0x8661
GL_MAP1_VERTEX_ATTRIB2_4_NV = 0x8662
GL_MAP1_VERTEX_ATTRIB3_4_NV = 0x8663
GL_MAP1_VERTEX_ATTRIB4_4_NV = 0x8664
GL_MAP1_VERTEX_ATTRIB5_4_NV = 0x8665
GL_MAP1_VERTEX_ATTRIB6_4_NV = 0x8666
GL_MAP1_VERTEX_ATTRIB7_4_NV = 0x8667
GL_MAP1_VERTEX_ATTRIB8_4_NV = 0x8668
GL_MAP1_VERTEX_ATTRIB9_4_NV = 0x8669
GL_MAP1_VERTEX_ATTRIB10_4_NV = 0x866A
GL_MAP1_VERTEX_ATTRIB11_4_NV = 0x866B
GL_MAP1_VERTEX_ATTRIB12_4_NV = 0x866C
GL_MAP1_VERTEX_ATTRIB13_4_NV = 0x866D
GL_MAP1_VERTEX_ATTRIB14_4_NV = 0x866E
GL_MAP1_VERTEX_ATTRIB15_4_NV = 0x866F
GL_MAP2_VERTEX_ATTRIB0_4_NV = 0x8670
GL_MAP2_VERTEX_ATTRIB1_4_NV = 0x8671
GL_MAP2_VERTEX_ATTRIB2_4_NV = 0x8672
GL_MAP2_VERTEX_ATTRIB3_4_NV = 0x8673
GL_MAP2_VERTEX_ATTRIB4_4_NV = 0x8674
GL_MAP2_VERTEX_ATTRIB5_4_NV = 0x8675
GL_MAP2_VERTEX_ATTRIB6_4_NV = 0x8676
GL_MAP2_VERTEX_ATTRIB7_4_NV = 0x8677
GL_MAP2_VERTEX_ATTRIB8_4_NV = 0x8678
GL_MAP2_VERTEX_ATTRIB9_4_NV = 0x8679
GL_MAP2_VERTEX_ATTRIB10_4_NV = 0x867A
GL_MAP2_VERTEX_ATTRIB11_4_NV = 0x867B
GL_MAP2_VERTEX_ATTRIB12_4_NV = 0x867C
GL_MAP2_VERTEX_ATTRIB13_4_NV = 0x867D
GL_MAP2_VERTEX_ATTRIB14_4_NV = 0x867E
GL_MAP2_VERTEX_ATTRIB15_4_NV = 0x867F
glAreProgramsResidentNV = _get_function('glAreProgramsResidentNV', [_ctypes.c_int, _ctypes.POINTER(_ctypes.c_uint), _ctypes.POINTER(_ctypes.c_ubyte)], _ctypes.c_ubyte)
glBindProgramNV = _get_function('glBindProgramNV', [_ctypes.c_uint, _ctypes.c_uint], None)
glDeleteProgramsNV = _get_function('glDeleteProgramsNV', [_ctypes.c_int, _ctypes.POINTER(_ctypes.c_uint)], None)
glExecuteProgramNV = _get_function('glExecuteProgramNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glGenProgramsNV = _get_function('glGenProgramsNV', [_ctypes.c_int, _ctypes.POINTER(_ctypes.c_uint)], None)
glGetProgramParameterdvNV = _get_function('glGetProgramParameterdvNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glGetProgramParameterfvNV = _get_function('glGetProgramParameterfvNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glGetProgramStringNV = _get_function('glGetProgramStringNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_ubyte)], None)
glGetProgramivNV = _get_function('glGetProgramivNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glGetTrackMatrixivNV = _get_function('glGetTrackMatrixivNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glGetVertexAttribPointervNV = _get_function('glGetVertexAttribPointervNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_void_p)], None)
glGetVertexAttribdvNV = _get_function('glGetVertexAttribdvNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glGetVertexAttribfvNV = _get_function('glGetVertexAttribfvNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glGetVertexAttribivNV = _get_function('glGetVertexAttribivNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glIsProgramNV = _get_function('glIsProgramNV', [_ctypes.c_uint], _ctypes.c_ubyte)
glLoadProgramNV = _get_function('glLoadProgramNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_ubyte)], None)
glProgramParameter4dNV = _get_function('glProgramParameter4dNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double], None)
glProgramParameter4dvNV = _get_function('glProgramParameter4dvNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glProgramParameter4fNV = _get_function('glProgramParameter4fNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glProgramParameter4fvNV = _get_function('glProgramParameter4fvNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glProgramParameters4dvNV = _get_function('glProgramParameters4dvNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glProgramParameters4fvNV = _get_function('glProgramParameters4fvNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glRequestResidentProgramsNV = _get_function('glRequestResidentProgramsNV', [_ctypes.c_int, _ctypes.POINTER(_ctypes.c_uint)], None)
glTrackMatrixNV = _get_function('glTrackMatrixNV', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_uint, _ctypes.c_uint], None)
glVertexAttrib1dNV = _get_function('glVertexAttrib1dNV', [_ctypes.c_uint, _ctypes.c_double], None)
glVertexAttrib1dvNV = _get_function('glVertexAttrib1dvNV', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttrib1fNV = _get_function('glVertexAttrib1fNV', [_ctypes.c_uint, _ctypes.c_float], None)
glVertexAttrib1fvNV = _get_function('glVertexAttrib1fvNV', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttrib1sNV = _get_function('glVertexAttrib1sNV', [_ctypes.c_uint, _ctypes.c_short], None)
glVertexAttrib1svNV = _get_function('glVertexAttrib1svNV', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttrib2dNV = _get_function('glVertexAttrib2dNV', [_ctypes.c_uint, _ctypes.c_double, _ctypes.c_double], None)
glVertexAttrib2dvNV = _get_function('glVertexAttrib2dvNV', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttrib2fNV = _get_function('glVertexAttrib2fNV', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float], None)
glVertexAttrib2fvNV = _get_function('glVertexAttrib2fvNV', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttrib2sNV = _get_function('glVertexAttrib2sNV', [_ctypes.c_uint, _ctypes.c_short, _ctypes.c_short], None)
glVertexAttrib2svNV = _get_function('glVertexAttrib2svNV', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttrib3dNV = _get_function('glVertexAttrib3dNV', [_ctypes.c_uint, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double], None)
glVertexAttrib3dvNV = _get_function('glVertexAttrib3dvNV', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttrib3fNV = _get_function('glVertexAttrib3fNV', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glVertexAttrib3fvNV = _get_function('glVertexAttrib3fvNV', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttrib3sNV = _get_function('glVertexAttrib3sNV', [_ctypes.c_uint, _ctypes.c_short, _ctypes.c_short, _ctypes.c_short], None)
glVertexAttrib3svNV = _get_function('glVertexAttrib3svNV', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttrib4dNV = _get_function('glVertexAttrib4dNV', [_ctypes.c_uint, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double], None)
glVertexAttrib4dvNV = _get_function('glVertexAttrib4dvNV', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttrib4fNV = _get_function('glVertexAttrib4fNV', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glVertexAttrib4fvNV = _get_function('glVertexAttrib4fvNV', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttrib4sNV = _get_function('glVertexAttrib4sNV', [_ctypes.c_uint, _ctypes.c_short, _ctypes.c_short, _ctypes.c_short, _ctypes.c_short], None)
glVertexAttrib4svNV = _get_function('glVertexAttrib4svNV', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttrib4ubNV = _get_function('glVertexAttrib4ubNV', [_ctypes.c_uint, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_ubyte], None)
glVertexAttrib4ubvNV = _get_function('glVertexAttrib4ubvNV', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_ubyte)], None)
glVertexAttribPointerNV = _get_function('glVertexAttribPointerNV', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_void_p], None)
glVertexAttribs1dvNV = _get_function('glVertexAttribs1dvNV', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttribs1fvNV = _get_function('glVertexAttribs1fvNV', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttribs1svNV = _get_function('glVertexAttribs1svNV', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttribs2dvNV = _get_function('glVertexAttribs2dvNV', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttribs2fvNV = _get_function('glVertexAttribs2fvNV', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttribs2svNV = _get_function('glVertexAttribs2svNV', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttribs3dvNV = _get_function('glVertexAttribs3dvNV', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttribs3fvNV = _get_function('glVertexAttribs3fvNV', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttribs3svNV = _get_function('glVertexAttribs3svNV', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttribs4dvNV = _get_function('glVertexAttribs4dvNV', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttribs4fvNV = _get_function('glVertexAttribs4fvNV', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttribs4svNV = _get_function('glVertexAttribs4svNV', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttribs4ubvNV = _get_function('glVertexAttribs4ubvNV', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_ubyte)], None)
