
"""SUN_vertex
http://oss.sgi.com/projects/ogl-sample/registry/SUN/vertex.txt
"""

import ctypes as _ctypes
from pyglet.GL import get_function as _get_function
from pyglet.GL import c_ptrdiff_t as _c_ptrdiff_t
glColor3fVertex3fSUN = _get_function('glColor3fVertex3fSUN', [_ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glColor3fVertex3fvSUN = _get_function('glColor3fVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
glColor4fNormal3fVertex3fSUN = _get_function('glColor4fNormal3fVertex3fSUN', [_ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glColor4fNormal3fVertex3fvSUN = _get_function('glColor4fNormal3fVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
glColor4ubVertex2fSUN = _get_function('glColor4ubVertex2fSUN', [_ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_float, _ctypes.c_float], None)
glColor4ubVertex2fvSUN = _get_function('glColor4ubVertex2fvSUN', [_ctypes.c_char_p, _ctypes.POINTER(_ctypes.c_float)], None)
glColor4ubVertex3fSUN = _get_function('glColor4ubVertex3fSUN', [_ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glColor4ubVertex3fvSUN = _get_function('glColor4ubVertex3fvSUN', [_ctypes.c_char_p, _ctypes.POINTER(_ctypes.c_float)], None)
glNormal3fVertex3fSUN = _get_function('glNormal3fVertex3fSUN', [_ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glNormal3fVertex3fvSUN = _get_function('glNormal3fVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
glReplacementCodeuiColor3fVertex3fSUN = _get_function('glReplacementCodeuiColor3fVertex3fSUN', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glReplacementCodeuiColor3fVertex3fvSUN = _get_function('glReplacementCodeuiColor3fVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_uint), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
glReplacementCodeuiColor4fNormal3fVertex3fSUN = _get_function('glReplacementCodeuiColor4fNormal3fVertex3fSUN', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glReplacementCodeuiColor4fNormal3fVertex3fvSUN = _get_function('glReplacementCodeuiColor4fNormal3fVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_uint), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
glReplacementCodeuiColor4ubVertex3fSUN = _get_function('glReplacementCodeuiColor4ubVertex3fSUN', [_ctypes.c_uint, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glReplacementCodeuiColor4ubVertex3fvSUN = _get_function('glReplacementCodeuiColor4ubVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_uint), _ctypes.c_char_p, _ctypes.POINTER(_ctypes.c_float)], None)
glReplacementCodeuiNormal3fVertex3fSUN = _get_function('glReplacementCodeuiNormal3fVertex3fSUN', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glReplacementCodeuiNormal3fVertex3fvSUN = _get_function('glReplacementCodeuiNormal3fVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_uint), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fSUN = _get_function('glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fSUN', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN = _get_function('glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_uint), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
glReplacementCodeuiTexCoord2fNormal3fVertex3fSUN = _get_function('glReplacementCodeuiTexCoord2fNormal3fVertex3fSUN', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN = _get_function('glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_uint), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
glReplacementCodeuiTexCoord2fVertex3fSUN = _get_function('glReplacementCodeuiTexCoord2fVertex3fSUN', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glReplacementCodeuiTexCoord2fVertex3fvSUN = _get_function('glReplacementCodeuiTexCoord2fVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_uint), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
glReplacementCodeuiVertex3fSUN = _get_function('glReplacementCodeuiVertex3fSUN', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glReplacementCodeuiVertex3fvSUN = _get_function('glReplacementCodeuiVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_uint), _ctypes.POINTER(_ctypes.c_float)], None)
glTexCoord2fColor3fVertex3fSUN = _get_function('glTexCoord2fColor3fVertex3fSUN', [_ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glTexCoord2fColor3fVertex3fvSUN = _get_function('glTexCoord2fColor3fVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
glTexCoord2fColor4fNormal3fVertex3fSUN = _get_function('glTexCoord2fColor4fNormal3fVertex3fSUN', [_ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glTexCoord2fColor4fNormal3fVertex3fvSUN = _get_function('glTexCoord2fColor4fNormal3fVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
glTexCoord2fColor4ubVertex3fSUN = _get_function('glTexCoord2fColor4ubVertex3fSUN', [_ctypes.c_float, _ctypes.c_float, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glTexCoord2fColor4ubVertex3fvSUN = _get_function('glTexCoord2fColor4ubVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_float), _ctypes.c_char_p, _ctypes.POINTER(_ctypes.c_float)], None)
glTexCoord2fNormal3fVertex3fSUN = _get_function('glTexCoord2fNormal3fVertex3fSUN', [_ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glTexCoord2fNormal3fVertex3fvSUN = _get_function('glTexCoord2fNormal3fVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
glTexCoord2fVertex3fSUN = _get_function('glTexCoord2fVertex3fSUN', [_ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glTexCoord2fVertex3fvSUN = _get_function('glTexCoord2fVertex3fvSUN', [_ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
glTexCoord4fColor4fNormal3fVertex4fSUN = _get_function('glTexCoord4fColor4fNormal3fVertex4fSUN', [_ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glTexCoord4fColor4fNormal3fVertex4fvSUN = _get_function('glTexCoord4fColor4fNormal3fVertex4fvSUN', [_ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
glTexCoord4fVertex4fSUN = _get_function('glTexCoord4fVertex4fSUN', [_ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glTexCoord4fVertex4fvSUN = _get_function('glTexCoord4fVertex4fvSUN', [_ctypes.POINTER(_ctypes.c_float), _ctypes.POINTER(_ctypes.c_float)], None)
