
"""VERSION_2_0
http://www.opengl.org/documentation/specs/version2.0/glspec20.pdf
"""

import ctypes as _ctypes
from pyglet.GL import get_function as _get_function
from pyglet.GL import c_ptrdiff_t as _c_ptrdiff_t
from pyglet.GL.VERSION_1_5 import *
GL_BLEND_EQUATION_RGB = 0x8009
GL_VERTEX_ATTRIB_ARRAY_ENABLED = 0x8622
GL_VERTEX_ATTRIB_ARRAY_SIZE = 0x8623
GL_VERTEX_ATTRIB_ARRAY_STRIDE = 0x8624
GL_VERTEX_ATTRIB_ARRAY_TYPE = 0x8625
GL_CURRENT_VERTEX_ATTRIB = 0x8626
GL_VERTEX_PROGRAM_POINT_SIZE = 0x8642
GL_VERTEX_PROGRAM_TWO_SIDE = 0x8643
GL_VERTEX_ATTRIB_ARRAY_POINTER = 0x8645
GL_STENCIL_BACK_FUNC = 0x8800
GL_STENCIL_BACK_FAIL = 0x8801
GL_STENCIL_BACK_PASS_DEPTH_FAIL = 0x8802
GL_STENCIL_BACK_PASS_DEPTH_PASS = 0x8803
GL_MAX_DRAW_BUFFERS = 0x8824
GL_DRAW_BUFFER0 = 0x8825
GL_DRAW_BUFFER1 = 0x8826
GL_DRAW_BUFFER2 = 0x8827
GL_DRAW_BUFFER3 = 0x8828
GL_DRAW_BUFFER4 = 0x8829
GL_DRAW_BUFFER5 = 0x882A
GL_DRAW_BUFFER6 = 0x882B
GL_DRAW_BUFFER7 = 0x882C
GL_DRAW_BUFFER8 = 0x882D
GL_DRAW_BUFFER9 = 0x882E
GL_DRAW_BUFFER10 = 0x882F
GL_DRAW_BUFFER11 = 0x8830
GL_DRAW_BUFFER12 = 0x8831
GL_DRAW_BUFFER13 = 0x8832
GL_DRAW_BUFFER14 = 0x8833
GL_DRAW_BUFFER15 = 0x8834
GL_BLEND_EQUATION_ALPHA = 0x883D
GL_POINT_SPRITE = 0x8861
GL_COORD_REPLACE = 0x8862
GL_MAX_VERTEX_ATTRIBS = 0x8869
GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = 0x886A
GL_MAX_TEXTURE_COORDS = 0x8871
GL_MAX_TEXTURE_IMAGE_UNITS = 0x8872
GL_FRAGMENT_SHADER = 0x8B30
GL_VERTEX_SHADER = 0x8B31
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x8B49
GL_MAX_VERTEX_UNIFORM_COMPONENTS = 0x8B4A
GL_MAX_VARYING_FLOATS = 0x8B4B
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 0x8B4C
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0x8B4D
GL_SHADER_TYPE = 0x8B4F
GL_FLOAT_VEC2 = 0x8B50
GL_FLOAT_VEC3 = 0x8B51
GL_FLOAT_VEC4 = 0x8B52
GL_INT_VEC2 = 0x8B53
GL_INT_VEC3 = 0x8B54
GL_INT_VEC4 = 0x8B55
GL_BOOL = 0x8B56
GL_BOOL_VEC2 = 0x8B57
GL_BOOL_VEC3 = 0x8B58
GL_BOOL_VEC4 = 0x8B59
GL_FLOAT_MAT2 = 0x8B5A
GL_FLOAT_MAT3 = 0x8B5B
GL_FLOAT_MAT4 = 0x8B5C
GL_SAMPLER_1D = 0x8B5D
GL_SAMPLER_2D = 0x8B5E
GL_SAMPLER_3D = 0x8B5F
GL_SAMPLER_CUBE = 0x8B60
GL_SAMPLER_1D_SHADOW = 0x8B61
GL_SAMPLER_2D_SHADOW = 0x8B62
GL_DELETE_STATUS = 0x8B80
GL_COMPILE_STATUS = 0x8B81
GL_LINK_STATUS = 0x8B82
GL_VALIDATE_STATUS = 0x8B83
GL_INFO_LOG_LENGTH = 0x8B84
GL_ATTACHED_SHADERS = 0x8B85
GL_ACTIVE_UNIFORMS = 0x8B86
GL_ACTIVE_UNIFORM_MAX_LENGTH = 0x8B87
GL_SHADER_SOURCE_LENGTH = 0x8B88
GL_ACTIVE_ATTRIBUTES = 0x8B89
GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = 0x8B8A
GL_FRAGMENT_SHADER_DERIVATIVE_HINT = 0x8B8B
GL_SHADING_LANGUAGE_VERSION = 0x8B8C
GL_CURRENT_PROGRAM = 0x8B8D
GL_POINT_SPRITE_COORD_ORIGIN = 0x8CA0
GL_LOWER_LEFT = 0x8CA1
GL_UPPER_LEFT = 0x8CA2
GL_STENCIL_BACK_REF = 0x8CA3
GL_STENCIL_BACK_VALUE_MASK = 0x8CA4
GL_STENCIL_BACK_WRITEMASK = 0x8CA5
GLchar = _ctypes.c_char
glBlendEquationSeparate = _get_function('glBlendEquationSeparate', [_ctypes.c_uint, _ctypes.c_uint], None)
glDrawBuffers = _get_function('glDrawBuffers', [_ctypes.c_int, _ctypes.POINTER(_ctypes.c_uint)], None)
glStencilOpSeparate = _get_function('glStencilOpSeparate', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_uint, _ctypes.c_uint], None)
glStencilFuncSeparate = _get_function('glStencilFuncSeparate', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_uint], None)
glStencilMaskSeparate = _get_function('glStencilMaskSeparate', [_ctypes.c_uint, _ctypes.c_uint], None)
glAttachShader = _get_function('glAttachShader', [_ctypes.c_uint, _ctypes.c_uint], None)
glBindAttribLocation = _get_function('glBindAttribLocation', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(GLchar)], None)
glCompileShader = _get_function('glCompileShader', [_ctypes.c_uint], None)
glCreateProgram = _get_function('glCreateProgram', [], _ctypes.c_uint)
glCreateShader = _get_function('glCreateShader', [_ctypes.c_uint], _ctypes.c_uint)
glDeleteProgram = _get_function('glDeleteProgram', [_ctypes.c_uint], None)
glDeleteShader = _get_function('glDeleteShader', [_ctypes.c_uint], None)
glDetachShader = _get_function('glDetachShader', [_ctypes.c_uint, _ctypes.c_uint], None)
glDisableVertexAttribArray = _get_function('glDisableVertexAttribArray', [_ctypes.c_uint], None)
glEnableVertexAttribArray = _get_function('glEnableVertexAttribArray', [_ctypes.c_uint], None)
glGetActiveAttrib = _get_function('glGetActiveAttrib', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_int), _ctypes.POINTER(_ctypes.c_int), _ctypes.POINTER(_ctypes.c_uint), _ctypes.POINTER(GLchar)], None)
glGetActiveUniform = _get_function('glGetActiveUniform', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_int), _ctypes.POINTER(_ctypes.c_int), _ctypes.POINTER(_ctypes.c_uint), _ctypes.POINTER(GLchar)], None)
glGetAttachedShaders = _get_function('glGetAttachedShaders', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_int), _ctypes.POINTER(_ctypes.c_uint)], None)
glGetAttribLocation = _get_function('glGetAttribLocation', [_ctypes.c_uint, _ctypes.POINTER(GLchar)], _ctypes.c_int)
glGetProgramiv = _get_function('glGetProgramiv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glGetProgramInfoLog = _get_function('glGetProgramInfoLog', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_int), _ctypes.POINTER(GLchar)], None)
glGetShaderiv = _get_function('glGetShaderiv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glGetShaderInfoLog = _get_function('glGetShaderInfoLog', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_int), _ctypes.POINTER(GLchar)], None)
glShaderSource = _get_function('glShaderSource', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.POINTER(GLchar)), _ctypes.POINTER(_ctypes.c_int)], None)
glGetUniformLocation = _get_function('glGetUniformLocation', [_ctypes.c_int, _ctypes.POINTER(GLchar)], _ctypes.c_int)
glGetUniformfv = _get_function('glGetUniformfv', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_float)], None)
glGetUniformiv = _get_function('glGetUniformiv', [_ctypes.c_uint, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_int)], None)
glGetVertexAttribdv = _get_function('glGetVertexAttribdv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glGetVertexAttribfv = _get_function('glGetVertexAttribfv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glGetVertexAttribiv = _get_function('glGetVertexAttribiv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glGetVertexAttribPointerv = _get_function('glGetVertexAttribPointerv', [_ctypes.c_uint, _ctypes.c_uint, _ctypes.c_void_p], None)
glIsProgram = _get_function('glIsProgram', [_ctypes.c_uint], _ctypes.c_ubyte)
glIsShader = _get_function('glIsShader', [_ctypes.c_uint], _ctypes.c_ubyte)
glLinkProgram = _get_function('glLinkProgram', [_ctypes.c_uint], None)
glGetShaderSource = _get_function('glGetShaderSource', [_ctypes.c_int, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_int), _ctypes.POINTER(GLchar)], None)
glUseProgram = _get_function('glUseProgram', [_ctypes.c_uint], None)
glUniform1f = _get_function('glUniform1f', [_ctypes.c_int, _ctypes.c_float], None)
glUniform1fv = _get_function('glUniform1fv', [_ctypes.c_int, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_float)], None)
glUniform1i = _get_function('glUniform1i', [_ctypes.c_int, _ctypes.c_int], None)
glUniform1iv = _get_function('glUniform1iv', [_ctypes.c_int, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_int)], None)
glUniform2f = _get_function('glUniform2f', [_ctypes.c_int, _ctypes.c_float, _ctypes.c_float], None)
glUniform2fv = _get_function('glUniform2fv', [_ctypes.c_int, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_float)], None)
glUniform2i = _get_function('glUniform2i', [_ctypes.c_int, _ctypes.c_int, _ctypes.c_int], None)
glUniform2iv = _get_function('glUniform2iv', [_ctypes.c_int, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_int)], None)
glUniform3f = _get_function('glUniform3f', [_ctypes.c_int, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glUniform3fv = _get_function('glUniform3fv', [_ctypes.c_int, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_float)], None)
glUniform3i = _get_function('glUniform3i', [_ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int], None)
glUniform3iv = _get_function('glUniform3iv', [_ctypes.c_int, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_int)], None)
glUniform4f = _get_function('glUniform4f', [_ctypes.c_int, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glUniform4fv = _get_function('glUniform4fv', [_ctypes.c_int, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_float)], None)
glUniform4i = _get_function('glUniform4i', [_ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int], None)
glUniform4iv = _get_function('glUniform4iv', [_ctypes.c_int, _ctypes.c_int, _ctypes.POINTER(_ctypes.c_int)], None)
glUniformMatrix2fv = _get_function('glUniformMatrix2fv', [_ctypes.c_int, _ctypes.c_int, _ctypes.c_ubyte, _ctypes.POINTER(_ctypes.c_float)], None)
glUniformMatrix3fv = _get_function('glUniformMatrix3fv', [_ctypes.c_int, _ctypes.c_int, _ctypes.c_ubyte, _ctypes.POINTER(_ctypes.c_float)], None)
glUniformMatrix4fv = _get_function('glUniformMatrix4fv', [_ctypes.c_int, _ctypes.c_int, _ctypes.c_ubyte, _ctypes.POINTER(_ctypes.c_float)], None)
glValidateProgram = _get_function('glValidateProgram', [_ctypes.c_uint], None)
glVertexAttrib1d = _get_function('glVertexAttrib1d', [_ctypes.c_uint, _ctypes.c_double], None)
glVertexAttrib1dv = _get_function('glVertexAttrib1dv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttrib1f = _get_function('glVertexAttrib1f', [_ctypes.c_uint, _ctypes.c_float], None)
glVertexAttrib1fv = _get_function('glVertexAttrib1fv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttrib1s = _get_function('glVertexAttrib1s', [_ctypes.c_uint, _ctypes.c_short], None)
glVertexAttrib1sv = _get_function('glVertexAttrib1sv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttrib2d = _get_function('glVertexAttrib2d', [_ctypes.c_uint, _ctypes.c_double, _ctypes.c_double], None)
glVertexAttrib2dv = _get_function('glVertexAttrib2dv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttrib2f = _get_function('glVertexAttrib2f', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float], None)
glVertexAttrib2fv = _get_function('glVertexAttrib2fv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttrib2s = _get_function('glVertexAttrib2s', [_ctypes.c_uint, _ctypes.c_short, _ctypes.c_short], None)
glVertexAttrib2sv = _get_function('glVertexAttrib2sv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttrib3d = _get_function('glVertexAttrib3d', [_ctypes.c_uint, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double], None)
glVertexAttrib3dv = _get_function('glVertexAttrib3dv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttrib3f = _get_function('glVertexAttrib3f', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glVertexAttrib3fv = _get_function('glVertexAttrib3fv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttrib3s = _get_function('glVertexAttrib3s', [_ctypes.c_uint, _ctypes.c_short, _ctypes.c_short, _ctypes.c_short], None)
glVertexAttrib3sv = _get_function('glVertexAttrib3sv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttrib4Nbv = _get_function('glVertexAttrib4Nbv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_byte)], None)
glVertexAttrib4Niv = _get_function('glVertexAttrib4Niv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glVertexAttrib4Nsv = _get_function('glVertexAttrib4Nsv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttrib4Nub = _get_function('glVertexAttrib4Nub', [_ctypes.c_uint, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_ubyte, _ctypes.c_ubyte], None)
glVertexAttrib4Nubv = _get_function('glVertexAttrib4Nubv', [_ctypes.c_uint, _ctypes.c_char_p], None)
glVertexAttrib4Nuiv = _get_function('glVertexAttrib4Nuiv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_uint)], None)
glVertexAttrib4Nusv = _get_function('glVertexAttrib4Nusv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_ushort)], None)
glVertexAttrib4bv = _get_function('glVertexAttrib4bv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_byte)], None)
glVertexAttrib4d = _get_function('glVertexAttrib4d', [_ctypes.c_uint, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double], None)
glVertexAttrib4dv = _get_function('glVertexAttrib4dv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glVertexAttrib4f = _get_function('glVertexAttrib4f', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glVertexAttrib4fv = _get_function('glVertexAttrib4fv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glVertexAttrib4iv = _get_function('glVertexAttrib4iv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glVertexAttrib4s = _get_function('glVertexAttrib4s', [_ctypes.c_uint, _ctypes.c_short, _ctypes.c_short, _ctypes.c_short, _ctypes.c_short], None)
glVertexAttrib4sv = _get_function('glVertexAttrib4sv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glVertexAttrib4ubv = _get_function('glVertexAttrib4ubv', [_ctypes.c_uint, _ctypes.c_char_p], None)
glVertexAttrib4uiv = _get_function('glVertexAttrib4uiv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_uint)], None)
glVertexAttrib4usv = _get_function('glVertexAttrib4usv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_ushort)], None)
glVertexAttribPointer = _get_function('glVertexAttribPointer', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_ubyte, _ctypes.c_int, _ctypes.c_void_p], None)
