
"""VERSION_1_3
GL_TEXTURE0 0x84C0
"""

import ctypes as _ctypes
from pyglet.GL import get_function as _get_function
from pyglet.GL import c_ptrdiff_t as _c_ptrdiff_t
from pyglet.GL.VERSION_1_2 import *
GL_TEXTURE1 = 0x84C1
GL_TEXTURE2 = 0x84C2
GL_TEXTURE3 = 0x84C3
GL_TEXTURE4 = 0x84C4
GL_TEXTURE5 = 0x84C5
GL_TEXTURE6 = 0x84C6
GL_TEXTURE7 = 0x84C7
GL_TEXTURE8 = 0x84C8
GL_TEXTURE9 = 0x84C9
GL_TEXTURE10 = 0x84CA
GL_TEXTURE11 = 0x84CB
GL_TEXTURE12 = 0x84CC
GL_TEXTURE13 = 0x84CD
GL_TEXTURE14 = 0x84CE
GL_TEXTURE15 = 0x84CF
GL_TEXTURE16 = 0x84D0
GL_TEXTURE17 = 0x84D1
GL_TEXTURE18 = 0x84D2
GL_TEXTURE19 = 0x84D3
GL_TEXTURE20 = 0x84D4
GL_TEXTURE21 = 0x84D5
GL_TEXTURE22 = 0x84D6
GL_TEXTURE23 = 0x84D7
GL_TEXTURE24 = 0x84D8
GL_TEXTURE25 = 0x84D9
GL_TEXTURE26 = 0x84DA
GL_TEXTURE27 = 0x84DB
GL_TEXTURE28 = 0x84DC
GL_TEXTURE29 = 0x84DD
GL_TEXTURE30 = 0x84DE
GL_TEXTURE31 = 0x84DF
GL_ACTIVE_TEXTURE = 0x84E0
GL_CLIENT_ACTIVE_TEXTURE = 0x84E1
GL_MAX_TEXTURE_UNITS = 0x84E2
GL_NORMAL_MAP = 0x8511
GL_REFLECTION_MAP = 0x8512
GL_TEXTURE_CUBE_MAP = 0x8513
GL_TEXTURE_BINDING_CUBE_MAP = 0x8514
GL_TEXTURE_CUBE_MAP_POSITIVE_X = 0x8515
GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 0x8516
GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 0x8517
GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x8518
GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 0x8519
GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x851A
GL_PROXY_TEXTURE_CUBE_MAP = 0x851B
GL_MAX_CUBE_MAP_TEXTURE_SIZE = 0x851C
GL_COMPRESSED_ALPHA = 0x84E9
GL_COMPRESSED_LUMINANCE = 0x84EA
GL_COMPRESSED_LUMINANCE_ALPHA = 0x84EB
GL_COMPRESSED_INTENSITY = 0x84EC
GL_COMPRESSED_RGB = 0x84ED
GL_COMPRESSED_RGBA = 0x84EE
GL_TEXTURE_COMPRESSION_HINT = 0x84EF
GL_TEXTURE_COMPRESSED_IMAGE_SIZE = 0x86A0
GL_TEXTURE_COMPRESSED = 0x86A1
GL_NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2
GL_COMPRESSED_TEXTURE_FORMATS = 0x86A3
GL_MULTISAMPLE = 0x809D
GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E
GL_SAMPLE_ALPHA_TO_ONE = 0x809F
GL_SAMPLE_COVERAGE = 0x80A0
GL_SAMPLE_BUFFERS = 0x80A8
GL_SAMPLES = 0x80A9
GL_SAMPLE_COVERAGE_VALUE = 0x80AA
GL_SAMPLE_COVERAGE_INVERT = 0x80AB
GL_MULTISAMPLE_BIT = 0x20000000
GL_TRANSPOSE_MODELVIEW_MATRIX = 0x84E3
GL_TRANSPOSE_PROJECTION_MATRIX = 0x84E4
GL_TRANSPOSE_TEXTURE_MATRIX = 0x84E5
GL_TRANSPOSE_COLOR_MATRIX = 0x84E6
GL_COMBINE = 0x8570
GL_COMBINE_RGB = 0x8571
GL_COMBINE_ALPHA = 0x8572
GL_SOURCE0_RGB = 0x8580
GL_SOURCE1_RGB = 0x8581
GL_SOURCE2_RGB = 0x8582
GL_SOURCE0_ALPHA = 0x8588
GL_SOURCE1_ALPHA = 0x8589
GL_SOURCE2_ALPHA = 0x858A
GL_OPERAND0_RGB = 0x8590
GL_OPERAND1_RGB = 0x8591
GL_OPERAND2_RGB = 0x8592
GL_OPERAND0_ALPHA = 0x8598
GL_OPERAND1_ALPHA = 0x8599
GL_OPERAND2_ALPHA = 0x859A
GL_RGB_SCALE = 0x8573
GL_ADD_SIGNED = 0x8574
GL_INTERPOLATE = 0x8575
GL_SUBTRACT = 0x84E7
GL_CONSTANT = 0x8576
GL_PRIMARY_COLOR = 0x8577
GL_PREVIOUS = 0x8578
GL_DOT3_RGB = 0x86AE
GL_DOT3_RGBA = 0x86AF
GL_CLAMP_TO_BORDER = 0x812D
glActiveTexture = _get_function('glActiveTexture', [_ctypes.c_uint], None)
glClientActiveTexture = _get_function('glClientActiveTexture', [_ctypes.c_uint], None)
glCompressedTexImage1D = _get_function('glCompressedTexImage1D', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_void_p], None)
glCompressedTexImage2D = _get_function('glCompressedTexImage2D', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_void_p], None)
glCompressedTexImage3D = _get_function('glCompressedTexImage3D', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_void_p], None)
glCompressedTexSubImage1D = _get_function('glCompressedTexSubImage1D', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_void_p], None)
glCompressedTexSubImage2D = _get_function('glCompressedTexSubImage2D', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_void_p], None)
glCompressedTexSubImage3D = _get_function('glCompressedTexSubImage3D', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_uint, _ctypes.c_int, _ctypes.c_void_p], None)
glGetCompressedTexImage = _get_function('glGetCompressedTexImage', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_void_p], None)
glLoadTransposeMatrixd = _get_function('glLoadTransposeMatrixd', [_ctypes.c_double], None)
glLoadTransposeMatrixf = _get_function('glLoadTransposeMatrixf', [_ctypes.c_float], None)
glMultTransposeMatrixd = _get_function('glMultTransposeMatrixd', [_ctypes.c_double], None)
glMultTransposeMatrixf = _get_function('glMultTransposeMatrixf', [_ctypes.c_float], None)
glMultiTexCoord1d = _get_function('glMultiTexCoord1d', [_ctypes.c_uint, _ctypes.c_double], None)
glMultiTexCoord1dv = _get_function('glMultiTexCoord1dv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glMultiTexCoord1f = _get_function('glMultiTexCoord1f', [_ctypes.c_uint, _ctypes.c_float], None)
glMultiTexCoord1fv = _get_function('glMultiTexCoord1fv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glMultiTexCoord1i = _get_function('glMultiTexCoord1i', [_ctypes.c_uint, _ctypes.c_int], None)
glMultiTexCoord1iv = _get_function('glMultiTexCoord1iv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glMultiTexCoord1s = _get_function('glMultiTexCoord1s', [_ctypes.c_uint, _ctypes.c_short], None)
glMultiTexCoord1sv = _get_function('glMultiTexCoord1sv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glMultiTexCoord2d = _get_function('glMultiTexCoord2d', [_ctypes.c_uint, _ctypes.c_double, _ctypes.c_double], None)
glMultiTexCoord2dv = _get_function('glMultiTexCoord2dv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glMultiTexCoord2f = _get_function('glMultiTexCoord2f', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float], None)
glMultiTexCoord2fv = _get_function('glMultiTexCoord2fv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glMultiTexCoord2i = _get_function('glMultiTexCoord2i', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_int], None)
glMultiTexCoord2iv = _get_function('glMultiTexCoord2iv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glMultiTexCoord2s = _get_function('glMultiTexCoord2s', [_ctypes.c_uint, _ctypes.c_short, _ctypes.c_short], None)
glMultiTexCoord2sv = _get_function('glMultiTexCoord2sv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glMultiTexCoord3d = _get_function('glMultiTexCoord3d', [_ctypes.c_uint, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double], None)
glMultiTexCoord3dv = _get_function('glMultiTexCoord3dv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glMultiTexCoord3f = _get_function('glMultiTexCoord3f', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glMultiTexCoord3fv = _get_function('glMultiTexCoord3fv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glMultiTexCoord3i = _get_function('glMultiTexCoord3i', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int], None)
glMultiTexCoord3iv = _get_function('glMultiTexCoord3iv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glMultiTexCoord3s = _get_function('glMultiTexCoord3s', [_ctypes.c_uint, _ctypes.c_short, _ctypes.c_short, _ctypes.c_short], None)
glMultiTexCoord3sv = _get_function('glMultiTexCoord3sv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glMultiTexCoord4d = _get_function('glMultiTexCoord4d', [_ctypes.c_uint, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double, _ctypes.c_double], None)
glMultiTexCoord4dv = _get_function('glMultiTexCoord4dv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_double)], None)
glMultiTexCoord4f = _get_function('glMultiTexCoord4f', [_ctypes.c_uint, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float, _ctypes.c_float], None)
glMultiTexCoord4fv = _get_function('glMultiTexCoord4fv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_float)], None)
glMultiTexCoord4i = _get_function('glMultiTexCoord4i', [_ctypes.c_uint, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int, _ctypes.c_int], None)
glMultiTexCoord4iv = _get_function('glMultiTexCoord4iv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_int)], None)
glMultiTexCoord4s = _get_function('glMultiTexCoord4s', [_ctypes.c_uint, _ctypes.c_short, _ctypes.c_short, _ctypes.c_short, _ctypes.c_short], None)
glMultiTexCoord4sv = _get_function('glMultiTexCoord4sv', [_ctypes.c_uint, _ctypes.POINTER(_ctypes.c_short)], None)
glSampleCoverage = _get_function('glSampleCoverage', [_ctypes.c_float, _ctypes.c_ubyte], None)
