#!/usr/bin/env python

'''
'''

__docformat__ = 'restructuredtext'
__version__ = '$Id: $'

from pyglet.window.key import *
from pyglet.window.win32.constants import *

keymap = {
    ord('A'): K_A,
    ord('B'): K_B,
    ord('C'): K_C,
    ord('D'): K_D,
    ord('E'): K_E,
    ord('F'): K_F,
    ord('G'): K_G,
    ord('H'): K_H,
    ord('I'): K_I,
    ord('J'): K_J,
    ord('K'): K_K,
    ord('L'): K_L,
    ord('M'): K_M,
    ord('N'): K_N,
    ord('O'): K_O,
    ord('P'): K_P,
    ord('Q'): K_Q,
    ord('R'): K_R,
    ord('S'): K_S,
    ord('T'): K_T,
    ord('U'): K_U,
    ord('V'): K_V,
    ord('W'): K_W,
    ord('X'): K_X,
    ord('Y'): K_Y,
    ord('Z'): K_Z,
    ord('0'): K_0,
    ord('1'): K_1,
    ord('2'): K_2,
    ord('3'): K_3,
    ord('4'): K_4,
    ord('5'): K_5,
    ord('6'): K_6,
    ord('7'): K_7,
    ord('8'): K_8,
    ord('9'): K_9,
    ord('\b'): K_BACKSPACE,

    # Assume US-ASCII layout
    VK_OEM_7: K_APOSTROPHE, 
    VK_OEM_2: K_SLASH, 
    VK_OEM_1: K_SEMICOLON, 
    VK_OEM_4: K_BRACKETLEFT, 
    VK_OEM_5: K_BACKSLASH, 
    VK_OEM_6: K_BRACKETRIGHT, 
    VK_OEM_3: K_QUOTELEFT, 
    VK_OEM_PLUS: K_EQUAL, 
    VK_OEM_COMMA: K_COMMA, 
    VK_OEM_PERIOD: K_PERIOD, 
    VK_OEM_MINUS: K_MINUS,

    # By experiment:
    0x14: K_CAPSLOCK,
    0x5d: K_MENU,

#    VK_LBUTTON: , 
#    VK_RBUTTON: , 
    VK_CANCEL: K_CANCEL, 
#    VK_MBUTTON: , 
#    VK_BACK: , 
    VK_TAB: K_TAB, 
#    VK_CLEAR: , 
    VK_RETURN: K_RETURN, 
    VK_SHIFT: K_LSHIFT, 
    VK_CONTROL: K_LCTRL, 
    VK_MENU: K_LALT, 
    VK_PAUSE: K_PAUSE, 
#    VK_CAPITAL: , 
#    VK_KANA: , 
#    VK_HANGEUL: , 
#    VK_HANGUL: , 
#    VK_JUNJA: , 
#    VK_FINAL: , 
#    VK_HANJA: , 
#    VK_KANJI: , 
    VK_ESCAPE: K_ESCAPE, 
#    VK_CONVERT: , 
#    VK_NONCONVERT: , 
#    VK_ACCEPT: , 
#    VK_MODECHANGE: , 
    VK_SPACE: K_SPACE, 
    VK_PRIOR: K_PAGEUP, 
    VK_NEXT: K_PAGEDOWN, 
    VK_END: K_END, 
    VK_HOME: K_HOME, 
    VK_LEFT: K_LEFT, 
    VK_UP: K_UP, 
    VK_RIGHT: K_RIGHT, 
    VK_DOWN: K_DOWN, 
#    VK_SELECT: , 
    VK_PRINT: K_PRINT, 
#    VK_EXECUTE: , 
#    VK_SNAPSHOT: , 
    VK_INSERT: K_INSERT, 
    VK_DELETE: K_DELETE, 
    VK_HELP: K_HELP, 
    VK_LWIN: K_LWINDOWS, 
    VK_RWIN: K_RWINDOWS, 
#    VK_APPS: , 
    VK_NUMPAD0: K_NUM_0, 
    VK_NUMPAD1: K_NUM_1, 
    VK_NUMPAD2: K_NUM_2, 
    VK_NUMPAD3: K_NUM_3, 
    VK_NUMPAD4: K_NUM_4, 
    VK_NUMPAD5: K_NUM_5, 
    VK_NUMPAD6: K_NUM_6, 
    VK_NUMPAD7: K_NUM_7, 
    VK_NUMPAD8: K_NUM_8, 
    VK_NUMPAD9: K_NUM_9, 
    VK_MULTIPLY: K_NUM_MULTIPLY, 
    VK_ADD: K_NUM_ADD, 
#    VK_SEPARATOR: , 
    VK_SUBTRACT: K_NUM_SUBTRACT, 
    VK_DECIMAL: K_NUM_DECIMAL, 
    VK_DIVIDE: K_NUM_DIVIDE, 
    VK_F1: K_F1, 
    VK_F2: K_F2, 
    VK_F3: K_F3, 
    VK_F4: K_F4, 
    VK_F5: K_F5, 
    VK_F6: K_F6, 
    VK_F7: K_F7, 
    VK_F8: K_F8, 
    VK_F9: K_F9, 
    VK_F10: K_F10, 
    VK_F11: K_F11, 
    VK_F12: K_F12, 
    VK_F13: K_F13, 
    VK_F14: K_F14, 
    VK_F15: K_F15, 
    VK_F16: K_F16, 
#    VK_F17: , 
#    VK_F18: , 
#    VK_F19: , 
#    VK_F20: , 
#    VK_F21: , 
#    VK_F22: , 
#    VK_F23: , 
#    VK_F24: , 
    VK_NUMLOCK: K_NUMLOCK, 
    VK_SCROLL: K_SCROLLLOCK, 
    VK_LSHIFT: K_LSHIFT, 
    VK_RSHIFT: K_RSHIFT, 
    VK_LCONTROL: K_LCTRL, 
    VK_RCONTROL: K_RCTRL, 
    VK_LMENU: K_LALT, 
    VK_RMENU: K_RALT, 
#    VK_PROCESSKEY: , 
#    VK_ATTN: , 
#    VK_CRSEL: , 
#    VK_EXSEL: , 
#    VK_EREOF: , 
#    VK_PLAY: , 
#    VK_ZOOM: , 
#    VK_NONAME: , 
#    VK_PA1: , 
#    VK_OEM_CLEAR: , 
#    VK_XBUTTON1: , 
#    VK_XBUTTON2: , 
#    VK_VOLUME_MUTE: , 
#    VK_VOLUME_DOWN: , 
#    VK_VOLUME_UP: , 
#    VK_MEDIA_NEXT_TRACK: , 
#    VK_MEDIA_PREV_TRACK: , 
#    VK_MEDIA_PLAY_PAUSE: , 
#    VK_BROWSER_BACK: , 
#    VK_BROWSER_FORWARD: , 
}
