"""EGL ctypes bindings generated from tools/gen_opengl/egl.xml.

Generated by tools/gen_opengl/gen_egl.py. Do not modify this file.
"""
from __future__ import annotations

from ctypes import CFUNCTYPE, POINTER, c_byte, c_char_p, c_int, c_int64, c_ssize_t, c_uint, c_uint64, c_void_p

from pyglet.libs.egl.lib import link_EGL as _link_function
from pyglet.libs.linux.x11.xlib import Display, Pixmap, Window

# EGL type definitions
khronos_utime_nanoseconds_t = c_uint64
khronos_stime_nanoseconds_t = c_int64
khronos_ssize_t = c_ssize_t
EGLBoolean = c_uint
EGLenum = c_uint
EGLAttrib = c_ssize_t
EGLAttribKHR = c_ssize_t
EGLClientBuffer = c_void_p
EGLClientPixmapHI = c_byte
EGLConfig = c_void_p
EGLContext = c_void_p
EGLDisplay = c_void_p
EGLDeviceEXT = c_void_p
EGLImage = c_void_p
EGLImageKHR = c_void_p
EGLLabelKHR = c_void_p
EGLNativeFileDescriptorKHR = c_int
EGLNativeDisplayType = POINTER(Display)
EGLNativePixmapType = Pixmap
EGLNativeWindowType = Window
EGLObjectKHR = c_void_p
EGLOutputLayerEXT = c_void_p
EGLOutputPortEXT = c_void_p
EGLsizeiANDROID = c_ssize_t
EGLSetBlobFuncANDROID = CFUNCTYPE(None, c_void_p, EGLsizeiANDROID, c_void_p, EGLsizeiANDROID)
EGLGetBlobFuncANDROID = CFUNCTYPE(EGLsizeiANDROID, c_void_p, EGLsizeiANDROID, c_void_p, EGLsizeiANDROID)
EGLStreamKHR = c_void_p
EGLSurface = c_void_p
EGLSync = c_void_p
EGLSyncKHR = c_void_p
EGLSyncNV = c_void_p
EGLTime = khronos_utime_nanoseconds_t
EGLTimeKHR = khronos_utime_nanoseconds_t
EGLTimeNV = khronos_utime_nanoseconds_t
EGLint = c_int
EGLnsecsANDROID = khronos_stime_nanoseconds_t
EGLuint64KHR = c_uint64
EGLuint64NV = c_uint64
AHardwareBuffer = c_byte
wl_buffer = c_byte
wl_display = c_byte
wl_resource = c_byte
EGLDEBUGPROCKHR = CFUNCTYPE(None, EGLenum, c_char_p, EGLint, EGLLabelKHR, EGLLabelKHR, c_char_p)
__eglMustCastToProperFunctionPointerType = CFUNCTYPE(None)

# EGL enumerant/constant definitions
EGL_ALPHA_FORMAT = 0x3088
EGL_ALPHA_FORMAT_NONPRE = 0x308B
EGL_ALPHA_FORMAT_PRE = 0x308C
EGL_ALPHA_MASK_SIZE = 0x303E
EGL_ALPHA_SIZE = 0x3021
EGL_BACK_BUFFER = 0x3084
EGL_BAD_ACCESS = 0x3002
EGL_BAD_ALLOC = 0x3003
EGL_BAD_ATTRIBUTE = 0x3004
EGL_BAD_CONFIG = 0x3005
EGL_BAD_CONTEXT = 0x3006
EGL_BAD_CURRENT_SURFACE = 0x3007
EGL_BAD_DEVICE_EXT = 0x322B
EGL_BAD_DISPLAY = 0x3008
EGL_BAD_MATCH = 0x3009
EGL_BAD_NATIVE_PIXMAP = 0x300A
EGL_BAD_NATIVE_WINDOW = 0x300B
EGL_BAD_PARAMETER = 0x300C
EGL_BAD_SURFACE = 0x300D
EGL_BIND_TO_TEXTURE_RGB = 0x3039
EGL_BIND_TO_TEXTURE_RGBA = 0x303A
EGL_BLUE_SIZE = 0x3022
EGL_BUFFER_AGE_EXT = 0x313D
EGL_BUFFER_AGE_KHR = 0x313D
EGL_BUFFER_DESTROYED = 0x3095
EGL_BUFFER_PRESERVED = 0x3094
EGL_BUFFER_SIZE = 0x3020
EGL_CLIENT_APIS = 0x308D
EGL_CL_EVENT_HANDLE = 0x309C
EGL_COLORSPACE = 0x3087
EGL_COLORSPACE_LINEAR = 0x308A
EGL_COLORSPACE_sRGB = 0x3089
EGL_COLOR_BUFFER_TYPE = 0x303F
EGL_CONDITION_SATISFIED = 0x30F6
EGL_CONFIG_CAVEAT = 0x3027
EGL_CONFIG_ID = 0x3028
EGL_CONFORMANT = 0x3042
EGL_CONTEXT_CLIENT_TYPE = 0x3097
EGL_CONTEXT_CLIENT_VERSION = 0x3098
EGL_CONTEXT_FLAGS_KHR = 0x30FC
EGL_CONTEXT_LOST = 0x300E
EGL_CONTEXT_MAJOR_VERSION = 0x3098
EGL_CONTEXT_MAJOR_VERSION_KHR = 0x3098
EGL_CONTEXT_MINOR_VERSION = 0x30FB
EGL_CONTEXT_MINOR_VERSION_KHR = 0x30FB
EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT = 0x00000002
EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT_KHR = 0x00000002
EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT = 0x00000001
EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT_KHR = 0x00000001
EGL_CONTEXT_OPENGL_DEBUG = 0x31B0
EGL_CONTEXT_OPENGL_DEBUG_BIT_KHR = 0x00000001
EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE = 0x31B1
EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE_BIT_KHR = 0x00000002
EGL_CONTEXT_OPENGL_NO_ERROR_KHR = 0x31B3
EGL_CONTEXT_OPENGL_PROFILE_MASK = 0x30FD
EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR = 0x30FD
EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY = 0x31BD
EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR = 0x31BD
EGL_CONTEXT_OPENGL_ROBUST_ACCESS = 0x31B2
EGL_CONTEXT_OPENGL_ROBUST_ACCESS_BIT_KHR = 0x00000004
EGL_CORE_NATIVE_ENGINE = 0x305B
EGL_DEBUG_CALLBACK_KHR = 0x33B8
EGL_DEBUG_MSG_CRITICAL_KHR = 0x33B9
EGL_DEBUG_MSG_ERROR_KHR = 0x33BA
EGL_DEBUG_MSG_INFO_KHR = 0x33BC
EGL_DEBUG_MSG_WARN_KHR = 0x33BB
EGL_DEFAULT_DISPLAY = None
EGL_DEPTH_SIZE = 0x3025
EGL_DEVICE_EXT = 0x322C
EGL_DISPLAY_SCALING = 10000
EGL_DMA_BUF_PLANE0_FD_EXT = 0x3272
EGL_DMA_BUF_PLANE0_MODIFIER_HI_EXT = 0x3444
EGL_DMA_BUF_PLANE0_MODIFIER_LO_EXT = 0x3443
EGL_DMA_BUF_PLANE0_OFFSET_EXT = 0x3273
EGL_DMA_BUF_PLANE0_PITCH_EXT = 0x3274
EGL_DMA_BUF_PLANE1_FD_EXT = 0x3275
EGL_DMA_BUF_PLANE1_MODIFIER_HI_EXT = 0x3446
EGL_DMA_BUF_PLANE1_MODIFIER_LO_EXT = 0x3445
EGL_DMA_BUF_PLANE1_OFFSET_EXT = 0x3276
EGL_DMA_BUF_PLANE1_PITCH_EXT = 0x3277
EGL_DMA_BUF_PLANE2_FD_EXT = 0x3278
EGL_DMA_BUF_PLANE2_MODIFIER_HI_EXT = 0x3448
EGL_DMA_BUF_PLANE2_MODIFIER_LO_EXT = 0x3447
EGL_DMA_BUF_PLANE2_OFFSET_EXT = 0x3279
EGL_DMA_BUF_PLANE2_PITCH_EXT = 0x327A
EGL_DMA_BUF_PLANE3_FD_EXT = 0x3440
EGL_DMA_BUF_PLANE3_MODIFIER_HI_EXT = 0x344A
EGL_DMA_BUF_PLANE3_MODIFIER_LO_EXT = 0x3449
EGL_DMA_BUF_PLANE3_OFFSET_EXT = 0x3441
EGL_DMA_BUF_PLANE3_PITCH_EXT = 0x3442
EGL_DONT_CARE = -1
EGL_DRAW = 0x3059
EGL_EXTENSIONS = 0x3055
EGL_FALSE = 0
EGL_FOREVER = 0xFFFFFFFFFFFFFFFF
EGL_GL_COLORSPACE = 0x309D
EGL_GL_COLORSPACE_KHR = 0x309D
EGL_GL_COLORSPACE_LINEAR = 0x308A
EGL_GL_COLORSPACE_LINEAR_KHR = 0x308A
EGL_GL_COLORSPACE_SRGB = 0x3089
EGL_GL_COLORSPACE_SRGB_KHR = 0x3089
EGL_GL_RENDERBUFFER = 0x30B9
EGL_GL_TEXTURE_2D = 0x30B1
EGL_GL_TEXTURE_3D = 0x30B2
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 0x30B4
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x30B6
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x30B8
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X = 0x30B3
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 0x30B5
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 0x30B7
EGL_GL_TEXTURE_LEVEL = 0x30BC
EGL_GL_TEXTURE_ZOFFSET = 0x30BD
EGL_GREEN_SIZE = 0x3023
EGL_HEIGHT = 0x3056
EGL_HORIZONTAL_RESOLUTION = 0x3090
EGL_IMAGE_PRESERVED = 0x30D2
EGL_ITU_REC2020_EXT = 0x3281
EGL_ITU_REC601_EXT = 0x327F
EGL_ITU_REC709_EXT = 0x3280
EGL_LARGEST_PBUFFER = 0x3058
EGL_LEVEL = 0x3029
EGL_LINUX_DMA_BUF_EXT = 0x3270
EGL_LINUX_DRM_FOURCC_EXT = 0x3271
EGL_LOSE_CONTEXT_ON_RESET = 0x31BF
EGL_LOSE_CONTEXT_ON_RESET_KHR = 0x31BF
EGL_LUMINANCE_BUFFER = 0x308F
EGL_LUMINANCE_SIZE = 0x303D
EGL_MATCH_NATIVE_PIXMAP = 0x3041
EGL_MAX_PBUFFER_HEIGHT = 0x302A
EGL_MAX_PBUFFER_PIXELS = 0x302B
EGL_MAX_PBUFFER_WIDTH = 0x302C
EGL_MAX_SWAP_INTERVAL = 0x303C
EGL_MIN_SWAP_INTERVAL = 0x303B
EGL_MIPMAP_LEVEL = 0x3083
EGL_MIPMAP_TEXTURE = 0x3082
EGL_MULTISAMPLE_RESOLVE = 0x3099
EGL_MULTISAMPLE_RESOLVE_BOX = 0x309B
EGL_MULTISAMPLE_RESOLVE_BOX_BIT = 0x0200
EGL_MULTISAMPLE_RESOLVE_DEFAULT = 0x309A
EGL_NATIVE_PIXMAP_KHR = 0x30B0
EGL_NATIVE_RENDERABLE = 0x302D
EGL_NATIVE_VISUAL_ID = 0x302E
EGL_NATIVE_VISUAL_TYPE = 0x302F
EGL_NONE = 0x3038
EGL_NON_CONFORMANT_CONFIG = 0x3051
EGL_NOT_INITIALIZED = 0x3001
EGL_NO_CONFIG_KHR = None
EGL_NO_CONTEXT = None
EGL_NO_DEVICE_EXT = None
EGL_NO_DISPLAY = None
EGL_NO_IMAGE = None
EGL_NO_IMAGE_KHR = None
EGL_NO_RESET_NOTIFICATION = 0x31BE
EGL_NO_RESET_NOTIFICATION_KHR = 0x31BE
EGL_NO_SURFACE = None
EGL_NO_SYNC = None
EGL_NO_TEXTURE = 0x305C
EGL_OBJECT_CONTEXT_KHR = 0x33B2
EGL_OBJECT_DISPLAY_KHR = 0x33B1
EGL_OBJECT_IMAGE_KHR = 0x33B4
EGL_OBJECT_STREAM_KHR = 0x33B6
EGL_OBJECT_SURFACE_KHR = 0x33B3
EGL_OBJECT_SYNC_KHR = 0x33B5
EGL_OBJECT_THREAD_KHR = 0x33B0
EGL_OPENGL_API = 0x30A2
EGL_OPENGL_BIT = 0x0008
EGL_OPENGL_ES2_BIT = 0x0004
EGL_OPENGL_ES3_BIT = 0x00000040
EGL_OPENGL_ES3_BIT_KHR = 0x00000040
EGL_OPENGL_ES_API = 0x30A0
EGL_OPENGL_ES_BIT = 0x0001
EGL_OPENVG_API = 0x30A1
EGL_OPENVG_BIT = 0x0002
EGL_OPENVG_IMAGE = 0x3096
EGL_PBUFFER_BIT = 0x0001
EGL_PIXEL_ASPECT_RATIO = 0x3092
EGL_PIXMAP_BIT = 0x0002
EGL_PLATFORM_DEVICE_EXT = 0x313F
EGL_PLATFORM_GBM_KHR = 0x31D7
EGL_PLATFORM_GBM_MESA = 0x31D7
EGL_PLATFORM_WAYLAND_EXT = 0x31D8
EGL_PLATFORM_WAYLAND_KHR = 0x31D8
EGL_PLATFORM_X11_EXT = 0x31D5
EGL_PLATFORM_X11_KHR = 0x31D5
EGL_PLATFORM_X11_SCREEN_EXT = 0x31D6
EGL_PLATFORM_X11_SCREEN_KHR = 0x31D6
EGL_READ = 0x305A
EGL_RED_SIZE = 0x3024
EGL_RENDERABLE_TYPE = 0x3040
EGL_RENDER_BUFFER = 0x3086
EGL_RGB_BUFFER = 0x308E
EGL_SAMPLES = 0x3031
EGL_SAMPLE_BUFFERS = 0x3032
EGL_SAMPLE_RANGE_HINT_EXT = 0x327C
EGL_SIGNALED = 0x30F2
EGL_SINGLE_BUFFER = 0x3085
EGL_SLOW_CONFIG = 0x3050
EGL_STENCIL_SIZE = 0x3026
EGL_SUCCESS = 0x3000
EGL_SURFACE_TYPE = 0x3033
EGL_SWAP_BEHAVIOR = 0x3093
EGL_SWAP_BEHAVIOR_PRESERVED_BIT = 0x0400
EGL_SYNC_CL_EVENT = 0x30FE
EGL_SYNC_CL_EVENT_COMPLETE = 0x30FF
EGL_SYNC_CONDITION = 0x30F8
EGL_SYNC_CONDITION_KHR = 0x30F8
EGL_SYNC_FENCE = 0x30F9
EGL_SYNC_FENCE_KHR = 0x30F9
EGL_SYNC_FLUSH_COMMANDS_BIT = 0x0001
EGL_SYNC_PRIOR_COMMANDS_COMPLETE = 0x30F0
EGL_SYNC_PRIOR_COMMANDS_COMPLETE_KHR = 0x30F0
EGL_SYNC_STATUS = 0x30F1
EGL_SYNC_TYPE = 0x30F7
EGL_TEXTURE_2D = 0x305F
EGL_TEXTURE_FORMAT = 0x3080
EGL_TEXTURE_RGB = 0x305D
EGL_TEXTURE_RGBA = 0x305E
EGL_TEXTURE_TARGET = 0x3081
EGL_TIMEOUT_EXPIRED = 0x30F5
EGL_TRANSPARENT_BLUE_VALUE = 0x3035
EGL_TRANSPARENT_GREEN_VALUE = 0x3036
EGL_TRANSPARENT_RED_VALUE = 0x3037
EGL_TRANSPARENT_RGB = 0x3052
EGL_TRANSPARENT_TYPE = 0x3034
EGL_TRUE = 1
EGL_UNKNOWN = -1
EGL_UNSIGNALED = 0x30F3
EGL_VENDOR = 0x3053
EGL_VERSION = 0x3054
EGL_VERTICAL_RESOLUTION = 0x3091
EGL_VG_ALPHA_FORMAT = 0x3088
EGL_VG_ALPHA_FORMAT_NONPRE = 0x308B
EGL_VG_ALPHA_FORMAT_PRE = 0x308C
EGL_VG_ALPHA_FORMAT_PRE_BIT = 0x0040
EGL_VG_COLORSPACE = 0x3087
EGL_VG_COLORSPACE_LINEAR = 0x308A
EGL_VG_COLORSPACE_LINEAR_BIT = 0x0020
EGL_VG_COLORSPACE_sRGB = 0x3089
EGL_WIDTH = 0x3057
EGL_WINDOW_BIT = 0x0004
EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT = 0x327D
EGL_YUV_CHROMA_SITING_0_5_EXT = 0x3285
EGL_YUV_CHROMA_SITING_0_EXT = 0x3284
EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT = 0x327E
EGL_YUV_COLOR_SPACE_HINT_EXT = 0x327B
EGL_YUV_FULL_RANGE_EXT = 0x3282
EGL_YUV_NARROW_RANGE_EXT = 0x3283

# EGL command definitions
eglBindAPI = _link_function('eglBindAPI', c_uint, [c_uint], 'EGL 1.2')
eglBindTexImage = _link_function('eglBindTexImage', c_uint, [c_void_p, c_void_p, c_int], 'EGL 1.1')
eglChooseConfig = _link_function('eglChooseConfig', c_uint, [c_void_p, POINTER(c_int), POINTER(c_void_p), c_int, POINTER(c_int)], 'EGL 1.0')
eglClientWaitSync = _link_function('eglClientWaitSync', c_int, [c_void_p, c_void_p, c_int, khronos_utime_nanoseconds_t], 'EGL 1.5')
eglClientWaitSyncKHR = _link_function('eglClientWaitSyncKHR', c_int, [c_void_p, c_void_p, c_int, khronos_utime_nanoseconds_t], 'EGL EGL_KHR_fence_sync')
eglCopyBuffers = _link_function('eglCopyBuffers', c_uint, [c_void_p, c_void_p, Pixmap], 'EGL 1.0')
eglCreateContext = _link_function('eglCreateContext', c_void_p, [c_void_p, c_void_p, c_void_p, POINTER(c_int)], 'EGL 1.0')
eglCreateImage = _link_function('eglCreateImage', c_void_p, [c_void_p, c_void_p, c_uint, c_void_p, POINTER(c_ssize_t)], 'EGL 1.5')
eglCreateImageKHR = _link_function('eglCreateImageKHR', c_void_p, [c_void_p, c_void_p, c_uint, c_void_p, POINTER(c_int)], 'EGL EGL_KHR_image')
eglCreatePbufferFromClientBuffer = _link_function('eglCreatePbufferFromClientBuffer', c_void_p, [c_void_p, c_uint, c_void_p, c_void_p, POINTER(c_int)], 'EGL 1.2')
eglCreatePbufferSurface = _link_function('eglCreatePbufferSurface', c_void_p, [c_void_p, c_void_p, POINTER(c_int)], 'EGL 1.0')
eglCreatePixmapSurface = _link_function('eglCreatePixmapSurface', c_void_p, [c_void_p, c_void_p, Pixmap, POINTER(c_int)], 'EGL 1.0')
eglCreatePlatformPixmapSurface = _link_function('eglCreatePlatformPixmapSurface', c_void_p, [c_void_p, c_void_p, c_void_p, POINTER(c_ssize_t)], 'EGL 1.5')
eglCreatePlatformPixmapSurfaceEXT = _link_function('eglCreatePlatformPixmapSurfaceEXT', c_void_p, [c_void_p, c_void_p, c_void_p, POINTER(c_int)], 'EGL EGL_EXT_platform_base')
eglCreatePlatformWindowSurface = _link_function('eglCreatePlatformWindowSurface', c_void_p, [c_void_p, c_void_p, c_void_p, POINTER(c_ssize_t)], 'EGL 1.5')
eglCreatePlatformWindowSurfaceEXT = _link_function('eglCreatePlatformWindowSurfaceEXT', c_void_p, [c_void_p, c_void_p, c_void_p, POINTER(c_int)], 'EGL EGL_EXT_platform_base')
eglCreateSync = _link_function('eglCreateSync', c_void_p, [c_void_p, c_uint, POINTER(c_ssize_t)], 'EGL 1.5')
eglCreateSyncKHR = _link_function('eglCreateSyncKHR', c_void_p, [c_void_p, c_uint, POINTER(c_int)], 'EGL EGL_KHR_fence_sync')
eglCreateWindowSurface = _link_function('eglCreateWindowSurface', c_void_p, [c_void_p, c_void_p, Window, POINTER(c_int)], 'EGL 1.0')
eglDebugMessageControlKHR = _link_function('eglDebugMessageControlKHR', c_int, [CFUNCTYPE(None, EGLenum, c_char_p, EGLint, EGLLabelKHR, EGLLabelKHR, c_char_p), POINTER(c_ssize_t)], 'EGL EGL_KHR_debug')
eglDestroyContext = _link_function('eglDestroyContext', c_uint, [c_void_p, c_void_p], 'EGL 1.0')
eglDestroyImage = _link_function('eglDestroyImage', c_uint, [c_void_p, c_void_p], 'EGL 1.5')
eglDestroyImageKHR = _link_function('eglDestroyImageKHR', c_uint, [c_void_p, c_void_p], 'EGL EGL_KHR_image')
eglDestroySurface = _link_function('eglDestroySurface', c_uint, [c_void_p, c_void_p], 'EGL 1.0')
eglDestroySync = _link_function('eglDestroySync', c_uint, [c_void_p, c_void_p], 'EGL 1.5')
eglDestroySyncKHR = _link_function('eglDestroySyncKHR', c_uint, [c_void_p, c_void_p], 'EGL EGL_KHR_fence_sync')
eglGetConfigAttrib = _link_function('eglGetConfigAttrib', c_uint, [c_void_p, c_void_p, c_int, POINTER(c_int)], 'EGL 1.0')
eglGetConfigs = _link_function('eglGetConfigs', c_uint, [c_void_p, POINTER(c_void_p), c_int, POINTER(c_int)], 'EGL 1.0')
eglGetCurrentContext = _link_function('eglGetCurrentContext', c_void_p, [], 'EGL 1.4')
eglGetCurrentDisplay = _link_function('eglGetCurrentDisplay', c_void_p, [], 'EGL 1.0')
eglGetCurrentSurface = _link_function('eglGetCurrentSurface', c_void_p, [c_int], 'EGL 1.0')
eglGetDisplay = _link_function('eglGetDisplay', c_void_p, [POINTER(Display)], 'EGL 1.0')
eglGetError = _link_function('eglGetError', c_int, [], 'EGL 1.0')
eglGetPlatformDisplay = _link_function('eglGetPlatformDisplay', c_void_p, [c_uint, c_void_p, POINTER(c_ssize_t)], 'EGL 1.5')
eglGetPlatformDisplayEXT = _link_function('eglGetPlatformDisplayEXT', c_void_p, [c_uint, c_void_p, POINTER(c_int)], 'EGL EGL_EXT_platform_base')
eglGetProcAddress = _link_function('eglGetProcAddress', CFUNCTYPE(None), [c_char_p], 'EGL 1.0')
eglGetSyncAttrib = _link_function('eglGetSyncAttrib', c_uint, [c_void_p, c_void_p, c_int, POINTER(c_ssize_t)], 'EGL 1.5')
eglGetSyncAttribKHR = _link_function('eglGetSyncAttribKHR', c_uint, [c_void_p, c_void_p, c_int, POINTER(c_int)], 'EGL EGL_KHR_fence_sync')
eglInitialize = _link_function('eglInitialize', c_uint, [c_void_p, POINTER(c_int), POINTER(c_int)], 'EGL 1.0')
eglLabelObjectKHR = _link_function('eglLabelObjectKHR', c_int, [c_void_p, c_uint, c_void_p, c_void_p], 'EGL EGL_KHR_debug')
eglMakeCurrent = _link_function('eglMakeCurrent', c_uint, [c_void_p, c_void_p, c_void_p, c_void_p], 'EGL 1.0')
eglQueryAPI = _link_function('eglQueryAPI', c_uint, [], 'EGL 1.2')
eglQueryContext = _link_function('eglQueryContext', c_uint, [c_void_p, c_void_p, c_int, POINTER(c_int)], 'EGL 1.0')
eglQueryDebugKHR = _link_function('eglQueryDebugKHR', c_uint, [c_int, POINTER(c_ssize_t)], 'EGL EGL_KHR_debug')
eglQueryDeviceAttribEXT = _link_function('eglQueryDeviceAttribEXT', c_uint, [c_void_p, c_int, POINTER(c_ssize_t)], 'EGL EGL_EXT_device_query')
eglQueryDeviceStringEXT = _link_function('eglQueryDeviceStringEXT', c_char_p, [c_void_p, c_int], 'EGL EGL_EXT_device_query')
eglQueryDevicesEXT = _link_function('eglQueryDevicesEXT', c_uint, [c_int, POINTER(c_void_p), POINTER(c_int)], 'EGL EGL_EXT_device_enumeration')
eglQueryDisplayAttribEXT = _link_function('eglQueryDisplayAttribEXT', c_uint, [c_void_p, c_int, POINTER(c_ssize_t)], 'EGL EGL_EXT_device_query')
eglQueryDmaBufFormatsEXT = _link_function('eglQueryDmaBufFormatsEXT', c_uint, [c_void_p, c_int, POINTER(c_int), POINTER(c_int)], 'EGL EGL_EXT_image_dma_buf_import_modifiers')
eglQueryDmaBufModifiersEXT = _link_function('eglQueryDmaBufModifiersEXT', c_uint, [c_void_p, c_int, c_int, POINTER(c_uint64), POINTER(c_uint), POINTER(c_int)], 'EGL EGL_EXT_image_dma_buf_import_modifiers')
eglQueryString = _link_function('eglQueryString', c_char_p, [c_void_p, c_int], 'EGL 1.0')
eglQuerySurface = _link_function('eglQuerySurface', c_uint, [c_void_p, c_void_p, c_int, POINTER(c_int)], 'EGL 1.0')
eglReleaseTexImage = _link_function('eglReleaseTexImage', c_uint, [c_void_p, c_void_p, c_int], 'EGL 1.1')
eglReleaseThread = _link_function('eglReleaseThread', c_uint, [], 'EGL 1.2')
eglSetDamageRegionKHR = _link_function('eglSetDamageRegionKHR', c_uint, [c_void_p, c_void_p, POINTER(c_int), c_int], 'EGL EGL_KHR_partial_update')
eglSurfaceAttrib = _link_function('eglSurfaceAttrib', c_uint, [c_void_p, c_void_p, c_int, c_int], 'EGL 1.1')
eglSwapBuffers = _link_function('eglSwapBuffers', c_uint, [c_void_p, c_void_p], 'EGL 1.0')
eglSwapBuffersWithDamageKHR = _link_function('eglSwapBuffersWithDamageKHR', c_uint, [c_void_p, c_void_p, POINTER(c_int), c_int], 'EGL EGL_KHR_swap_buffers_with_damage')
eglSwapInterval = _link_function('eglSwapInterval', c_uint, [c_void_p, c_int], 'EGL 1.1')
eglTerminate = _link_function('eglTerminate', c_uint, [c_void_p], 'EGL 1.0')
eglWaitClient = _link_function('eglWaitClient', c_uint, [], 'EGL 1.2')
eglWaitGL = _link_function('eglWaitGL', c_uint, [], 'EGL 1.0')
eglWaitNative = _link_function('eglWaitNative', c_uint, [c_int], 'EGL 1.0')
eglWaitSync = _link_function('eglWaitSync', c_uint, [c_void_p, c_void_p, c_int], 'EGL 1.5')
eglWaitSyncKHR = _link_function('eglWaitSyncKHR', c_int, [c_void_p, c_void_p, c_int], 'EGL EGL_KHR_wait_sync')

__all__ = [
    'khronos_utime_nanoseconds_t',
    'khronos_stime_nanoseconds_t',
    'khronos_ssize_t',
    'EGLBoolean',
    'EGLenum',
    'EGLAttrib',
    'EGLAttribKHR',
    'EGLClientBuffer',
    'EGLClientPixmapHI',
    'EGLConfig',
    'EGLContext',
    'EGLDisplay',
    'EGLDeviceEXT',
    'EGLImage',
    'EGLImageKHR',
    'EGLLabelKHR',
    'EGLNativeFileDescriptorKHR',
    'EGLNativeDisplayType',
    'EGLNativePixmapType',
    'EGLNativeWindowType',
    'EGLObjectKHR',
    'EGLOutputLayerEXT',
    'EGLOutputPortEXT',
    'EGLsizeiANDROID',
    'EGLSetBlobFuncANDROID',
    'EGLGetBlobFuncANDROID',
    'EGLStreamKHR',
    'EGLSurface',
    'EGLSync',
    'EGLSyncKHR',
    'EGLSyncNV',
    'EGLTime',
    'EGLTimeKHR',
    'EGLTimeNV',
    'EGLint',
    'EGLnsecsANDROID',
    'EGLuint64KHR',
    'EGLuint64NV',
    'AHardwareBuffer',
    'wl_buffer',
    'wl_display',
    'wl_resource',
    'EGLDEBUGPROCKHR',
    '__eglMustCastToProperFunctionPointerType',
    'EGL_ALPHA_SIZE',
    'EGL_BAD_ACCESS',
    'EGL_BAD_ALLOC',
    'EGL_BAD_ATTRIBUTE',
    'EGL_BAD_CONFIG',
    'EGL_BAD_CONTEXT',
    'EGL_BAD_CURRENT_SURFACE',
    'EGL_BAD_DISPLAY',
    'EGL_BAD_MATCH',
    'EGL_BAD_NATIVE_PIXMAP',
    'EGL_BAD_NATIVE_WINDOW',
    'EGL_BAD_PARAMETER',
    'EGL_BAD_SURFACE',
    'EGL_BLUE_SIZE',
    'EGL_BUFFER_SIZE',
    'EGL_CONFIG_CAVEAT',
    'EGL_CONFIG_ID',
    'EGL_CORE_NATIVE_ENGINE',
    'EGL_DEPTH_SIZE',
    'EGL_DONT_CARE',
    'EGL_DRAW',
    'EGL_EXTENSIONS',
    'EGL_FALSE',
    'EGL_GREEN_SIZE',
    'EGL_HEIGHT',
    'EGL_LARGEST_PBUFFER',
    'EGL_LEVEL',
    'EGL_MAX_PBUFFER_HEIGHT',
    'EGL_MAX_PBUFFER_PIXELS',
    'EGL_MAX_PBUFFER_WIDTH',
    'EGL_NATIVE_RENDERABLE',
    'EGL_NATIVE_VISUAL_ID',
    'EGL_NATIVE_VISUAL_TYPE',
    'EGL_NONE',
    'EGL_NON_CONFORMANT_CONFIG',
    'EGL_NOT_INITIALIZED',
    'EGL_NO_CONTEXT',
    'EGL_NO_DISPLAY',
    'EGL_NO_SURFACE',
    'EGL_PBUFFER_BIT',
    'EGL_PIXMAP_BIT',
    'EGL_READ',
    'EGL_RED_SIZE',
    'EGL_SAMPLES',
    'EGL_SAMPLE_BUFFERS',
    'EGL_SLOW_CONFIG',
    'EGL_STENCIL_SIZE',
    'EGL_SUCCESS',
    'EGL_SURFACE_TYPE',
    'EGL_TRANSPARENT_BLUE_VALUE',
    'EGL_TRANSPARENT_GREEN_VALUE',
    'EGL_TRANSPARENT_RED_VALUE',
    'EGL_TRANSPARENT_RGB',
    'EGL_TRANSPARENT_TYPE',
    'EGL_TRUE',
    'EGL_VENDOR',
    'EGL_VERSION',
    'EGL_WIDTH',
    'EGL_WINDOW_BIT',
    'EGL_BACK_BUFFER',
    'EGL_BIND_TO_TEXTURE_RGB',
    'EGL_BIND_TO_TEXTURE_RGBA',
    'EGL_CONTEXT_LOST',
    'EGL_MIN_SWAP_INTERVAL',
    'EGL_MAX_SWAP_INTERVAL',
    'EGL_MIPMAP_TEXTURE',
    'EGL_MIPMAP_LEVEL',
    'EGL_NO_TEXTURE',
    'EGL_TEXTURE_2D',
    'EGL_TEXTURE_FORMAT',
    'EGL_TEXTURE_RGB',
    'EGL_TEXTURE_RGBA',
    'EGL_TEXTURE_TARGET',
    'EGL_ALPHA_FORMAT',
    'EGL_ALPHA_FORMAT_NONPRE',
    'EGL_ALPHA_FORMAT_PRE',
    'EGL_ALPHA_MASK_SIZE',
    'EGL_BUFFER_PRESERVED',
    'EGL_BUFFER_DESTROYED',
    'EGL_CLIENT_APIS',
    'EGL_COLORSPACE',
    'EGL_COLORSPACE_sRGB',
    'EGL_COLORSPACE_LINEAR',
    'EGL_COLOR_BUFFER_TYPE',
    'EGL_CONTEXT_CLIENT_TYPE',
    'EGL_DISPLAY_SCALING',
    'EGL_HORIZONTAL_RESOLUTION',
    'EGL_LUMINANCE_BUFFER',
    'EGL_LUMINANCE_SIZE',
    'EGL_OPENGL_ES_BIT',
    'EGL_OPENVG_BIT',
    'EGL_OPENGL_ES_API',
    'EGL_OPENVG_API',
    'EGL_OPENVG_IMAGE',
    'EGL_PIXEL_ASPECT_RATIO',
    'EGL_RENDERABLE_TYPE',
    'EGL_RENDER_BUFFER',
    'EGL_RGB_BUFFER',
    'EGL_SINGLE_BUFFER',
    'EGL_SWAP_BEHAVIOR',
    'EGL_UNKNOWN',
    'EGL_VERTICAL_RESOLUTION',
    'EGL_CONFORMANT',
    'EGL_CONTEXT_CLIENT_VERSION',
    'EGL_MATCH_NATIVE_PIXMAP',
    'EGL_OPENGL_ES2_BIT',
    'EGL_VG_ALPHA_FORMAT',
    'EGL_VG_ALPHA_FORMAT_NONPRE',
    'EGL_VG_ALPHA_FORMAT_PRE',
    'EGL_VG_ALPHA_FORMAT_PRE_BIT',
    'EGL_VG_COLORSPACE',
    'EGL_VG_COLORSPACE_sRGB',
    'EGL_VG_COLORSPACE_LINEAR',
    'EGL_VG_COLORSPACE_LINEAR_BIT',
    'EGL_DEFAULT_DISPLAY',
    'EGL_MULTISAMPLE_RESOLVE_BOX_BIT',
    'EGL_MULTISAMPLE_RESOLVE',
    'EGL_MULTISAMPLE_RESOLVE_DEFAULT',
    'EGL_MULTISAMPLE_RESOLVE_BOX',
    'EGL_OPENGL_API',
    'EGL_OPENGL_BIT',
    'EGL_SWAP_BEHAVIOR_PRESERVED_BIT',
    'EGL_CONTEXT_MAJOR_VERSION',
    'EGL_CONTEXT_MINOR_VERSION',
    'EGL_CONTEXT_OPENGL_PROFILE_MASK',
    'EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY',
    'EGL_NO_RESET_NOTIFICATION',
    'EGL_LOSE_CONTEXT_ON_RESET',
    'EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT',
    'EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT',
    'EGL_CONTEXT_OPENGL_DEBUG',
    'EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE',
    'EGL_CONTEXT_OPENGL_ROBUST_ACCESS',
    'EGL_OPENGL_ES3_BIT',
    'EGL_CL_EVENT_HANDLE',
    'EGL_SYNC_CL_EVENT',
    'EGL_SYNC_CL_EVENT_COMPLETE',
    'EGL_SYNC_PRIOR_COMMANDS_COMPLETE',
    'EGL_SYNC_TYPE',
    'EGL_SYNC_STATUS',
    'EGL_SYNC_CONDITION',
    'EGL_SIGNALED',
    'EGL_UNSIGNALED',
    'EGL_SYNC_FLUSH_COMMANDS_BIT',
    'EGL_FOREVER',
    'EGL_TIMEOUT_EXPIRED',
    'EGL_CONDITION_SATISFIED',
    'EGL_NO_SYNC',
    'EGL_SYNC_FENCE',
    'EGL_GL_COLORSPACE',
    'EGL_GL_COLORSPACE_SRGB',
    'EGL_GL_COLORSPACE_LINEAR',
    'EGL_GL_RENDERBUFFER',
    'EGL_GL_TEXTURE_2D',
    'EGL_GL_TEXTURE_LEVEL',
    'EGL_GL_TEXTURE_3D',
    'EGL_GL_TEXTURE_ZOFFSET',
    'EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X',
    'EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X',
    'EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y',
    'EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y',
    'EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z',
    'EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z',
    'EGL_IMAGE_PRESERVED',
    'EGL_NO_IMAGE',
    'EGL_NO_DEVICE_EXT',
    'EGL_BAD_DEVICE_EXT',
    'EGL_DEVICE_EXT',
    'EGL_PLATFORM_DEVICE_EXT',
    'EGL_PLATFORM_WAYLAND_EXT',
    'EGL_PLATFORM_WAYLAND_KHR',
    'EGL_PLATFORM_X11_KHR',
    'EGL_PLATFORM_X11_SCREEN_KHR',
    'EGL_PLATFORM_X11_EXT',
    'EGL_PLATFORM_X11_SCREEN_EXT',
    'EGL_PLATFORM_GBM_KHR',
    'EGL_PLATFORM_GBM_MESA',
    'EGL_CONTEXT_MAJOR_VERSION_KHR',
    'EGL_CONTEXT_MINOR_VERSION_KHR',
    'EGL_CONTEXT_FLAGS_KHR',
    'EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR',
    'EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR',
    'EGL_NO_RESET_NOTIFICATION_KHR',
    'EGL_LOSE_CONTEXT_ON_RESET_KHR',
    'EGL_CONTEXT_OPENGL_DEBUG_BIT_KHR',
    'EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE_BIT_KHR',
    'EGL_CONTEXT_OPENGL_ROBUST_ACCESS_BIT_KHR',
    'EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT_KHR',
    'EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT_KHR',
    'EGL_OPENGL_ES3_BIT_KHR',
    'EGL_NO_CONFIG_KHR',
    'EGL_CONTEXT_OPENGL_NO_ERROR_KHR',
    'EGL_NATIVE_PIXMAP_KHR',
    'EGL_NO_IMAGE_KHR',
    'EGL_LINUX_DMA_BUF_EXT',
    'EGL_LINUX_DRM_FOURCC_EXT',
    'EGL_DMA_BUF_PLANE0_FD_EXT',
    'EGL_DMA_BUF_PLANE0_OFFSET_EXT',
    'EGL_DMA_BUF_PLANE0_PITCH_EXT',
    'EGL_DMA_BUF_PLANE1_FD_EXT',
    'EGL_DMA_BUF_PLANE1_OFFSET_EXT',
    'EGL_DMA_BUF_PLANE1_PITCH_EXT',
    'EGL_DMA_BUF_PLANE2_FD_EXT',
    'EGL_DMA_BUF_PLANE2_OFFSET_EXT',
    'EGL_DMA_BUF_PLANE2_PITCH_EXT',
    'EGL_YUV_COLOR_SPACE_HINT_EXT',
    'EGL_SAMPLE_RANGE_HINT_EXT',
    'EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT',
    'EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT',
    'EGL_ITU_REC601_EXT',
    'EGL_ITU_REC709_EXT',
    'EGL_ITU_REC2020_EXT',
    'EGL_YUV_FULL_RANGE_EXT',
    'EGL_YUV_NARROW_RANGE_EXT',
    'EGL_YUV_CHROMA_SITING_0_EXT',
    'EGL_YUV_CHROMA_SITING_0_5_EXT',
    'EGL_DMA_BUF_PLANE3_FD_EXT',
    'EGL_DMA_BUF_PLANE3_OFFSET_EXT',
    'EGL_DMA_BUF_PLANE3_PITCH_EXT',
    'EGL_DMA_BUF_PLANE0_MODIFIER_LO_EXT',
    'EGL_DMA_BUF_PLANE0_MODIFIER_HI_EXT',
    'EGL_DMA_BUF_PLANE1_MODIFIER_LO_EXT',
    'EGL_DMA_BUF_PLANE1_MODIFIER_HI_EXT',
    'EGL_DMA_BUF_PLANE2_MODIFIER_LO_EXT',
    'EGL_DMA_BUF_PLANE2_MODIFIER_HI_EXT',
    'EGL_DMA_BUF_PLANE3_MODIFIER_LO_EXT',
    'EGL_DMA_BUF_PLANE3_MODIFIER_HI_EXT',
    'EGL_SYNC_PRIOR_COMMANDS_COMPLETE_KHR',
    'EGL_SYNC_CONDITION_KHR',
    'EGL_SYNC_FENCE_KHR',
    'EGL_BUFFER_AGE_EXT',
    'EGL_BUFFER_AGE_KHR',
    'EGL_GL_COLORSPACE_KHR',
    'EGL_GL_COLORSPACE_SRGB_KHR',
    'EGL_GL_COLORSPACE_LINEAR_KHR',
    'EGL_OBJECT_THREAD_KHR',
    'EGL_OBJECT_DISPLAY_KHR',
    'EGL_OBJECT_CONTEXT_KHR',
    'EGL_OBJECT_SURFACE_KHR',
    'EGL_OBJECT_IMAGE_KHR',
    'EGL_OBJECT_SYNC_KHR',
    'EGL_OBJECT_STREAM_KHR',
    'EGL_DEBUG_MSG_CRITICAL_KHR',
    'EGL_DEBUG_MSG_ERROR_KHR',
    'EGL_DEBUG_MSG_WARN_KHR',
    'EGL_DEBUG_MSG_INFO_KHR',
    'EGL_DEBUG_CALLBACK_KHR',
    'eglBindAPI',
    'eglBindTexImage',
    'eglChooseConfig',
    'eglClientWaitSync',
    'eglClientWaitSyncKHR',
    'eglCopyBuffers',
    'eglCreateContext',
    'eglCreateImage',
    'eglCreateImageKHR',
    'eglCreatePbufferFromClientBuffer',
    'eglCreatePbufferSurface',
    'eglCreatePixmapSurface',
    'eglCreatePlatformPixmapSurface',
    'eglCreatePlatformPixmapSurfaceEXT',
    'eglCreatePlatformWindowSurface',
    'eglCreatePlatformWindowSurfaceEXT',
    'eglCreateSync',
    'eglCreateSyncKHR',
    'eglCreateWindowSurface',
    'eglDebugMessageControlKHR',
    'eglDestroyContext',
    'eglDestroyImage',
    'eglDestroyImageKHR',
    'eglDestroySurface',
    'eglDestroySync',
    'eglDestroySyncKHR',
    'eglGetConfigAttrib',
    'eglGetConfigs',
    'eglGetCurrentContext',
    'eglGetCurrentDisplay',
    'eglGetCurrentSurface',
    'eglGetDisplay',
    'eglGetError',
    'eglGetPlatformDisplay',
    'eglGetPlatformDisplayEXT',
    'eglGetProcAddress',
    'eglGetSyncAttrib',
    'eglGetSyncAttribKHR',
    'eglInitialize',
    'eglLabelObjectKHR',
    'eglMakeCurrent',
    'eglQueryAPI',
    'eglQueryContext',
    'eglQueryDebugKHR',
    'eglQueryDeviceAttribEXT',
    'eglQueryDeviceStringEXT',
    'eglQueryDevicesEXT',
    'eglQueryDisplayAttribEXT',
    'eglQueryDmaBufFormatsEXT',
    'eglQueryDmaBufModifiersEXT',
    'eglQueryString',
    'eglQuerySurface',
    'eglReleaseTexImage',
    'eglReleaseThread',
    'eglSetDamageRegionKHR',
    'eglSurfaceAttrib',
    'eglSwapBuffers',
    'eglSwapBuffersWithDamageKHR',
    'eglSwapInterval',
    'eglTerminate',
    'eglWaitClient',
    'eglWaitGL',
    'eglWaitNative',
    'eglWaitSync',
    'eglWaitSyncKHR',
]
