from __future__ import annotations

from pyglet.graphics.api.gl import (
    GL_LINEAR, GL_NEAREST, GL_TEXTURE_1D, GL_TEXTURE_2D, GL_TEXTURE_3D, \
    GL_TEXTURE_CUBE_MAP, \
    GL_TEXTURE_1D_ARRAY, GL_TEXTURE_2D_ARRAY, GL_TEXTURE_CUBE_MAP_ARRAY, GL_TEXTURE_WRAP_R, GL_TEXTURE_WRAP_S, \
    GL_TEXTURE_WRAP_T,
    GL_POINTS, GL_LINES, GL_LINE_STRIP, GL_TRIANGLES, GL_TRIANGLE_STRIP,
    GL_TRIANGLE_FAN, GL_PATCHES,
    GL_ZERO, GL_ONE, GL_SRC_COLOR, GL_ONE_MINUS_SRC_COLOR, GL_DST_COLOR,
    GL_ONE_MINUS_DST_COLOR, GL_SRC_ALPHA, \
    GL_ONE_MINUS_SRC_ALPHA, GL_DST_ALPHA, GL_ONE_MINUS_DST_ALPHA, GL_CONSTANT_COLOR,
    GL_ONE_MINUS_CONSTANT_COLOR, \
    GL_CONSTANT_ALPHA, GL_ONE_MINUS_CONSTANT_ALPHA, GL_NEVER, GL_LESS, GL_EQUAL, GL_LEQUAL, GL_GREATER, GL_NOTEQUAL,
    GL_GEQUAL, GL_ALWAYS, GL_KEEP, GL_ZERO, GL_REPLACE, GL_INCR, GL_INCR_WRAP, GL_DECR, GL_DECR_WRAP, GL_INVERT,
    GL_FUNC_ADD, GL_FUNC_SUBTRACT, GL_FUNC_REVERSE_SUBTRACT, GL_MIN, GL_MAX, GL_FRONT, GL_BACK, GL_FRONT_AND_BACK,
    GL_CW, GL_CCW)

from pyglet.enums import (
    BlendFactor, BlendOp, CompareOp, CullFace, FrontFace, GeometryMode, StencilOp, TextureFilter, TextureType,
    TextureWrapping,
)

geometry_map = {
    GeometryMode.POINTS: GL_POINTS,
    GeometryMode.LINES: GL_LINES,
    GeometryMode.LINE_STRIP: GL_LINE_STRIP,
    GeometryMode.TRIANGLES: GL_TRIANGLES,
    GeometryMode.TRIANGLE_STRIP: GL_TRIANGLE_STRIP,
    GeometryMode.TRIANGLE_FAN: GL_TRIANGLE_FAN,
    GeometryMode.PATCHES: GL_PATCHES,
}

blend_factor_map = {
    BlendFactor.ZERO: GL_ZERO,
    BlendFactor.ONE: GL_ONE,
    BlendFactor.SRC_COLOR: GL_SRC_COLOR,
    BlendFactor.ONE_MINUS_SRC_COLOR: GL_ONE_MINUS_SRC_COLOR,
    BlendFactor.DST_COLOR: GL_DST_COLOR,
    BlendFactor.ONE_MINUS_DST_COLOR: GL_ONE_MINUS_DST_COLOR,
    BlendFactor.SRC_ALPHA: GL_SRC_ALPHA,
    BlendFactor.ONE_MINUS_SRC_ALPHA: GL_ONE_MINUS_SRC_ALPHA,
    BlendFactor.DST_ALPHA: GL_DST_ALPHA,
    BlendFactor.ONE_MINUS_DST_ALPHA: GL_ONE_MINUS_DST_ALPHA,
    BlendFactor.CONSTANT_COLOR: GL_CONSTANT_COLOR,
    BlendFactor.ONE_MINUS_CONSTANT_COLOR: GL_ONE_MINUS_CONSTANT_COLOR,
    BlendFactor.CONSTANT_ALPHA: GL_CONSTANT_ALPHA,
    BlendFactor.ONE_MINUS_CONSTANT_ALPHA: GL_ONE_MINUS_CONSTANT_ALPHA,
}

texture_map = {
    # Filters
    TextureFilter.LINEAR: GL_LINEAR,
    TextureFilter.NEAREST: GL_NEAREST,

    # Texture Types
    TextureType.TYPE_1D: GL_TEXTURE_1D,
    TextureType.TYPE_2D: GL_TEXTURE_2D,
    TextureType.TYPE_3D: GL_TEXTURE_3D,
    TextureType.TYPE_CUBE_MAP: GL_TEXTURE_CUBE_MAP,
    TextureType.TYPE_1D_ARRAY: GL_TEXTURE_1D_ARRAY,
    TextureType.TYPE_2D_ARRAY: GL_TEXTURE_2D_ARRAY,
    TextureType.TYPE_CUBE_MAP_ARRAY: GL_TEXTURE_CUBE_MAP_ARRAY,

    # Wrapping
    TextureWrapping.WRAP_R: GL_TEXTURE_WRAP_R,
    TextureWrapping.WRAP_S: GL_TEXTURE_WRAP_S,
    TextureWrapping.WRAP_T: GL_TEXTURE_WRAP_T,
}


compare_op_map = {
    CompareOp.NEVER: GL_NEVER,
    CompareOp.LESS: GL_LESS,
    CompareOp.EQUAL: GL_EQUAL,
    CompareOp.LESS_OR_EQUAL: GL_LEQUAL,
    CompareOp.GREATER: GL_GREATER,
    CompareOp.NOT_EQUAL: GL_NOTEQUAL,
    CompareOp.GREATER_OR_EQUAL: GL_GEQUAL,
    CompareOp.ALWAYS: GL_ALWAYS,
}

blend_op_map = {
    BlendOp.ADD: GL_FUNC_ADD,
    BlendOp.SUBTRACT: GL_FUNC_SUBTRACT,
    BlendOp.REVERSE_SUBTRACT: GL_FUNC_REVERSE_SUBTRACT,
    BlendOp.MIN: GL_MIN,
    BlendOp.MAX: GL_MAX,
}

stencil_op_map = {
    StencilOp.KEEP: GL_KEEP,
    StencilOp.ZERO: GL_ZERO,
    StencilOp.REPLACE: GL_REPLACE,
    StencilOp.INCREMENT: GL_INCR,
    StencilOp.INCREMENT_WRAP: GL_INCR_WRAP,
    StencilOp.DECREMENT: GL_DECR,
    StencilOp.DECREMENT_WRAP: GL_DECR_WRAP,
    StencilOp.INVERT: GL_INVERT,
}

cull_face_map = {
    CullFace.FRONT: GL_FRONT,
    CullFace.BACK: GL_BACK,
    CullFace.FRONT_AND_BACK: GL_FRONT_AND_BACK,
}

front_face_map = {
    FrontFace.CLOCKWISE: GL_CW,
    FrontFace.COUNTER_CLOCKWISE: GL_CCW,
}
