"""GLX ctypes bindings generated from tools/gen_opengl/glx.xml.

Generated by tools/gen_opengl/gen_glx.py. Do not modify this file.
"""
from __future__ import annotations

from ctypes import CFUNCTYPE, POINTER, c_char_p, c_float, c_int, c_int32, c_int64, c_ssize_t, c_ubyte, c_uint, c_ulong, c_void_p

from pyglet.graphics.api.gl.lib import link_GLX as _link_function
from pyglet.libs.linux.x11.xlib import Display, Font, Pixmap, Window, XID, XVisualInfo

if not _link_function:
    msg = "libGL.so is not available."
    raise ImportError(msg)

# GLX type definitions
Bool = c_int
GLbitfield = c_uint
GLboolean = c_ubyte
GLenum = c_uint
GLfloat = c_float
GLint = c_int
GLintptr = c_ssize_t
GLsizei = c_int
GLsizeiptr = c_ssize_t
GLXContext = c_void_p
GLXContextID = XID
GLXDrawable = XID
GLXFBConfig = c_void_p
GLXFBConfigID = XID
GLXPbuffer = XID
GLXPixmap = XID
GLXWindow = XID
GLubyte = c_ubyte
GLuint = c_uint
GLvoid = None
__GLXextFuncPtr = CFUNCTYPE(None)

# GLX enumerant/constant definitions
GLX_ACCUM_ALPHA_SIZE = 17
GLX_ACCUM_BLUE_SIZE = 16
GLX_ACCUM_BUFFER_BIT = 0x00000080
GLX_ACCUM_GREEN_SIZE = 15
GLX_ACCUM_RED_SIZE = 14
GLX_ALPHA_SIZE = 11
GLX_AUX_BUFFERS = 7
GLX_AUX_BUFFERS_BIT = 0x00000010
GLX_BACK_LEFT_BUFFER_BIT = 0x00000004
GLX_BACK_RIGHT_BUFFER_BIT = 0x00000008
GLX_BAD_ATTRIBUTE = 2
GLX_BAD_CONTEXT = 5
GLX_BAD_ENUM = 7
GLX_BAD_SCREEN = 1
GLX_BAD_VALUE = 6
GLX_BAD_VISUAL = 4
GLX_BLUE_SIZE = 10
GLX_BUFFER_SIZE = 2
GLX_BufferSwapComplete = 1
GLX_COLOR_INDEX_BIT = 0x00000002
GLX_COLOR_INDEX_TYPE = 0x8015
GLX_CONFIG_CAVEAT = 0x20
GLX_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB = 0x00000002
GLX_CONTEXT_CORE_PROFILE_BIT_ARB = 0x00000001
GLX_CONTEXT_DEBUG_BIT_ARB = 0x00000001
GLX_CONTEXT_ES2_PROFILE_BIT_EXT = 0x00000004
GLX_CONTEXT_FLAGS_ARB = 0x2094
GLX_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB = 0x00000002
GLX_CONTEXT_MAJOR_VERSION_ARB = 0x2091
GLX_CONTEXT_MINOR_VERSION_ARB = 0x2092
GLX_CONTEXT_MULTIGPU_ATTRIB_AFR_NV = 0x20AC
GLX_CONTEXT_MULTIGPU_ATTRIB_MULTICAST_NV = 0x20AD
GLX_CONTEXT_MULTIGPU_ATTRIB_MULTI_DISPLAY_MULTICAST_NV = 0x20AE
GLX_CONTEXT_MULTIGPU_ATTRIB_NV = 0x20AA
GLX_CONTEXT_MULTIGPU_ATTRIB_SINGLE_NV = 0x20AB
GLX_CONTEXT_PROFILE_MASK_ARB = 0x9126
GLX_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB = 0x8256
GLX_CONTEXT_ROBUST_ACCESS_BIT_ARB = 0x00000004
GLX_DAMAGED = 0x8020
GLX_DEPTH_BUFFER_BIT = 0x00000020
GLX_DEPTH_SIZE = 12
GLX_DIRECT_COLOR = 0x8003
GLX_DONT_CARE = 0xFFFFFFFF
GLX_DOUBLEBUFFER = 5
GLX_DRAWABLE_TYPE = 0x8010
GLX_EVENT_MASK = 0x801F
GLX_EXTENSIONS = 0x3
GLX_EXTENSION_NAME = "GLX"
GLX_FBCONFIG_ID = 0x8013
GLX_FRONT_LEFT_BUFFER_BIT = 0x00000001
GLX_FRONT_RIGHT_BUFFER_BIT = 0x00000002
GLX_GRAY_SCALE = 0x8006
GLX_GREEN_SIZE = 9
GLX_HEIGHT = 0x801E
GLX_LARGEST_PBUFFER = 0x801C
GLX_LATE_SWAPS_TEAR_EXT = 0x20F3
GLX_LEVEL = 3
GLX_LOSE_CONTEXT_ON_RESET_ARB = 0x8252
GLX_MAX_PBUFFER_HEIGHT = 0x8017
GLX_MAX_PBUFFER_PIXELS = 0x8018
GLX_MAX_PBUFFER_WIDTH = 0x8016
GLX_MAX_SWAP_INTERVAL_EXT = 0x20F2
GLX_NONE = 0x8000
GLX_NON_CONFORMANT_CONFIG = 0x800D
GLX_NO_EXTENSION = 3
GLX_NO_RESET_NOTIFICATION_ARB = 0x8261
GLX_PBUFFER = 0x8023
GLX_PBUFFER_BIT = 0x00000004
GLX_PBUFFER_CLOBBER_MASK = 0x08000000
GLX_PBUFFER_HEIGHT = 0x8040
GLX_PBUFFER_WIDTH = 0x8041
GLX_PIXMAP_BIT = 0x00000002
GLX_PRESERVED_CONTENTS = 0x801B
GLX_PSEUDO_COLOR = 0x8004
GLX_PbufferClobber = 0
GLX_RED_SIZE = 8
GLX_RENDERER_ACCELERATED_MESA = 0x8186
GLX_RENDERER_DEVICE_ID_MESA = 0x8184
GLX_RENDERER_OPENGL_COMPATIBILITY_PROFILE_VERSION_MESA = 0x818B
GLX_RENDERER_OPENGL_CORE_PROFILE_VERSION_MESA = 0x818A
GLX_RENDERER_OPENGL_ES2_PROFILE_VERSION_MESA = 0x818D
GLX_RENDERER_OPENGL_ES_PROFILE_VERSION_MESA = 0x818C
GLX_RENDERER_PREFERRED_PROFILE_MESA = 0x8189
GLX_RENDERER_UNIFIED_MEMORY_ARCHITECTURE_MESA = 0x8188
GLX_RENDERER_VENDOR_ID_MESA = 0x8183
GLX_RENDERER_VERSION_MESA = 0x8185
GLX_RENDERER_VIDEO_MEMORY_MESA = 0x8187
GLX_RENDER_TYPE = 0x8011
GLX_RGBA = 4
GLX_RGBA_BIT = 0x00000001
GLX_RGBA_FLOAT_BIT_ARB = 0x00000004
GLX_RGBA_FLOAT_TYPE_ARB = 0x20B9
GLX_RGBA_TYPE = 0x8014
GLX_SAMPLES = 100001
GLX_SAMPLE_BUFFERS = 100000
GLX_SAVED = 0x8021
GLX_SCREEN = 0x800C
GLX_SCREEN_EXT = 0x800C
GLX_SHARE_CONTEXT_EXT = 0x800A
GLX_SLOW_CONFIG = 0x8001
GLX_STATIC_COLOR = 0x8005
GLX_STATIC_GRAY = 0x8007
GLX_STENCIL_BUFFER_BIT = 0x00000040
GLX_STENCIL_SIZE = 13
GLX_STEREO = 6
GLX_SWAP_INTERVAL_EXT = 0x20F1
GLX_TRANSPARENT_ALPHA_VALUE = 0x28
GLX_TRANSPARENT_BLUE_VALUE = 0x27
GLX_TRANSPARENT_GREEN_VALUE = 0x26
GLX_TRANSPARENT_INDEX = 0x8009
GLX_TRANSPARENT_INDEX_VALUE = 0x24
GLX_TRANSPARENT_RED_VALUE = 0x25
GLX_TRANSPARENT_RGB = 0x8008
GLX_TRANSPARENT_TYPE = 0x23
GLX_TRUE_COLOR = 0x8002
GLX_USE_GL = 1
GLX_VENDOR = 0x1
GLX_VERSION = 0x2
GLX_VISUAL_ID = 0x800B
GLX_VISUAL_ID_EXT = 0x800B
GLX_WIDTH = 0x801D
GLX_WINDOW = 0x8022
GLX_WINDOW_BIT = 0x00000001
GLX_X_RENDERABLE = 0x8012
GLX_X_VISUAL_TYPE = 0x22
__GLX_NUMBER_EVENTS = 17

# GLX command definitions
glXBindSwapBarrierNV = _link_function('glXBindSwapBarrierNV', c_int, [POINTER(Display), c_uint, c_uint], 'GLX GLX_NV_swap_group')
glXChooseFBConfig = _link_function('glXChooseFBConfig', POINTER(c_void_p), [POINTER(Display), c_int, POINTER(c_int), POINTER(c_int)], 'GLX 1.3')
glXChooseVisual = _link_function('glXChooseVisual', POINTER(XVisualInfo), [POINTER(Display), c_int, POINTER(c_int)], 'GLX 1.0')
glXCopyContext = _link_function('glXCopyContext', None, [POINTER(Display), c_void_p, c_void_p, c_ulong], 'GLX 1.0')
glXCreateContext = _link_function('glXCreateContext', c_void_p, [POINTER(Display), POINTER(XVisualInfo), c_void_p, c_int], 'GLX 1.0')
glXCreateContextAttribsARB = _link_function('glXCreateContextAttribsARB', c_void_p, [POINTER(Display), c_void_p, c_void_p, c_int, POINTER(c_int)], 'GLX GLX_ARB_create_context')
glXCreateGLXPixmap = _link_function('glXCreateGLXPixmap', XID, [POINTER(Display), POINTER(XVisualInfo), Pixmap], 'GLX 1.0')
glXCreateNewContext = _link_function('glXCreateNewContext', c_void_p, [POINTER(Display), c_void_p, c_int, c_void_p, c_int], 'GLX 1.3')
glXCreatePbuffer = _link_function('glXCreatePbuffer', XID, [POINTER(Display), c_void_p, POINTER(c_int)], 'GLX 1.3')
glXCreatePixmap = _link_function('glXCreatePixmap', XID, [POINTER(Display), c_void_p, Pixmap, POINTER(c_int)], 'GLX 1.3')
glXCreateWindow = _link_function('glXCreateWindow', XID, [POINTER(Display), c_void_p, Window, POINTER(c_int)], 'GLX 1.3')
glXDestroyContext = _link_function('glXDestroyContext', None, [POINTER(Display), c_void_p], 'GLX 1.0')
glXDestroyGLXPixmap = _link_function('glXDestroyGLXPixmap', None, [POINTER(Display), XID], 'GLX 1.0')
glXDestroyPbuffer = _link_function('glXDestroyPbuffer', None, [POINTER(Display), XID], 'GLX 1.3')
glXDestroyPixmap = _link_function('glXDestroyPixmap', None, [POINTER(Display), XID], 'GLX 1.3')
glXDestroyWindow = _link_function('glXDestroyWindow', None, [POINTER(Display), XID], 'GLX 1.3')
glXFreeContextEXT = _link_function('glXFreeContextEXT', None, [POINTER(Display), c_void_p], 'GLX GLX_EXT_import_context')
glXGetClientString = _link_function('glXGetClientString', c_char_p, [POINTER(Display), c_int], 'GLX 1.1')
glXGetConfig = _link_function('glXGetConfig', c_int, [POINTER(Display), POINTER(XVisualInfo), c_int, POINTER(c_int)], 'GLX 1.0')
glXGetContextIDEXT = _link_function('glXGetContextIDEXT', XID, [c_void_p], 'GLX GLX_EXT_import_context')
glXGetCurrentContext = _link_function('glXGetCurrentContext', c_void_p, [], 'GLX 1.0')
glXGetCurrentDisplay = _link_function('glXGetCurrentDisplay', POINTER(Display), [], 'GLX 1.2')
glXGetCurrentDisplayEXT = _link_function('glXGetCurrentDisplayEXT', POINTER(Display), [], 'GLX GLX_EXT_import_context')
glXGetCurrentDrawable = _link_function('glXGetCurrentDrawable', XID, [], 'GLX 1.0')
glXGetCurrentReadDrawable = _link_function('glXGetCurrentReadDrawable', XID, [], 'GLX 1.3')
glXGetFBConfigAttrib = _link_function('glXGetFBConfigAttrib', c_int, [POINTER(Display), c_void_p, c_int, POINTER(c_int)], 'GLX 1.3')
glXGetFBConfigs = _link_function('glXGetFBConfigs', POINTER(c_void_p), [POINTER(Display), c_int, POINTER(c_int)], 'GLX 1.3')
glXGetMscRateOML = _link_function('glXGetMscRateOML', c_int, [POINTER(Display), XID, POINTER(c_int32), POINTER(c_int32)], 'GLX GLX_OML_sync_control')
glXGetProcAddress = _link_function('glXGetProcAddress', CFUNCTYPE(None), [POINTER(c_ubyte)], 'GLX 1.4')
glXGetSelectedEvent = _link_function('glXGetSelectedEvent', None, [POINTER(Display), XID, POINTER(c_ulong)], 'GLX 1.3')
glXGetSwapIntervalMESA = _link_function('glXGetSwapIntervalMESA', c_int, [], 'GLX GLX_MESA_swap_control')
glXGetSyncValuesOML = _link_function('glXGetSyncValuesOML', c_int, [POINTER(Display), XID, POINTER(c_int64), POINTER(c_int64), POINTER(c_int64)], 'GLX GLX_OML_sync_control')
glXGetVideoSyncSGI = _link_function('glXGetVideoSyncSGI', c_int, [POINTER(c_uint)], 'GLX GLX_SGI_video_sync')
glXGetVisualFromFBConfig = _link_function('glXGetVisualFromFBConfig', POINTER(XVisualInfo), [POINTER(Display), c_void_p], 'GLX 1.3')
glXImportContextEXT = _link_function('glXImportContextEXT', c_void_p, [POINTER(Display), XID], 'GLX GLX_EXT_import_context')
glXIsDirect = _link_function('glXIsDirect', c_int, [POINTER(Display), c_void_p], 'GLX 1.0')
glXJoinSwapGroupNV = _link_function('glXJoinSwapGroupNV', c_int, [POINTER(Display), XID, c_uint], 'GLX GLX_NV_swap_group')
glXMakeContextCurrent = _link_function('glXMakeContextCurrent', c_int, [POINTER(Display), XID, XID, c_void_p], 'GLX 1.3')
glXMakeCurrent = _link_function('glXMakeCurrent', c_int, [POINTER(Display), XID, c_void_p], 'GLX 1.0')
glXQueryContext = _link_function('glXQueryContext', c_int, [POINTER(Display), c_void_p, c_int, POINTER(c_int)], 'GLX 1.3')
glXQueryContextInfoEXT = _link_function('glXQueryContextInfoEXT', c_int, [POINTER(Display), c_void_p, c_int, POINTER(c_int)], 'GLX GLX_EXT_import_context')
glXQueryCurrentRendererIntegerMESA = _link_function('glXQueryCurrentRendererIntegerMESA', c_int, [c_int, POINTER(c_uint)], 'GLX GLX_MESA_query_renderer')
glXQueryCurrentRendererStringMESA = _link_function('glXQueryCurrentRendererStringMESA', c_char_p, [c_int], 'GLX GLX_MESA_query_renderer')
glXQueryDrawable = _link_function('glXQueryDrawable', None, [POINTER(Display), XID, c_int, POINTER(c_uint)], 'GLX 1.3')
glXQueryExtension = _link_function('glXQueryExtension', c_int, [POINTER(Display), POINTER(c_int), POINTER(c_int)], 'GLX 1.0')
glXQueryExtensionsString = _link_function('glXQueryExtensionsString', c_char_p, [POINTER(Display), c_int], 'GLX 1.1')
glXQueryFrameCountNV = _link_function('glXQueryFrameCountNV', c_int, [POINTER(Display), c_int, POINTER(c_uint)], 'GLX GLX_NV_swap_group')
glXQueryMaxSwapGroupsNV = _link_function('glXQueryMaxSwapGroupsNV', c_int, [POINTER(Display), c_int, POINTER(c_uint), POINTER(c_uint)], 'GLX GLX_NV_swap_group')
glXQueryRendererIntegerMESA = _link_function('glXQueryRendererIntegerMESA', c_int, [POINTER(Display), c_int, c_int, c_int, POINTER(c_uint)], 'GLX GLX_MESA_query_renderer')
glXQueryRendererStringMESA = _link_function('glXQueryRendererStringMESA', c_char_p, [POINTER(Display), c_int, c_int, c_int], 'GLX GLX_MESA_query_renderer')
glXQueryServerString = _link_function('glXQueryServerString', c_char_p, [POINTER(Display), c_int, c_int], 'GLX 1.1')
glXQuerySwapGroupNV = _link_function('glXQuerySwapGroupNV', c_int, [POINTER(Display), XID, POINTER(c_uint), POINTER(c_uint)], 'GLX GLX_NV_swap_group')
glXQueryVersion = _link_function('glXQueryVersion', c_int, [POINTER(Display), POINTER(c_int), POINTER(c_int)], 'GLX 1.0')
glXResetFrameCountNV = _link_function('glXResetFrameCountNV', c_int, [POINTER(Display), c_int], 'GLX GLX_NV_swap_group')
glXSelectEvent = _link_function('glXSelectEvent', None, [POINTER(Display), XID, c_ulong], 'GLX 1.3')
glXSwapBuffers = _link_function('glXSwapBuffers', None, [POINTER(Display), XID], 'GLX 1.0')
glXSwapBuffersMscOML = _link_function('glXSwapBuffersMscOML', c_int64, [POINTER(Display), XID, c_int64, c_int64, c_int64], 'GLX GLX_OML_sync_control')
glXSwapIntervalEXT = _link_function('glXSwapIntervalEXT', None, [POINTER(Display), XID, c_int], 'GLX GLX_EXT_swap_control')
glXSwapIntervalMESA = _link_function('glXSwapIntervalMESA', c_int, [c_uint], 'GLX GLX_MESA_swap_control')
glXSwapIntervalSGI = _link_function('glXSwapIntervalSGI', c_int, [c_int], 'GLX GLX_SGI_swap_control')
glXUseXFont = _link_function('glXUseXFont', None, [Font, c_int, c_int, c_int], 'GLX 1.0')
glXWaitForMscOML = _link_function('glXWaitForMscOML', c_int, [POINTER(Display), XID, c_int64, c_int64, c_int64, POINTER(c_int64), POINTER(c_int64), POINTER(c_int64)], 'GLX GLX_OML_sync_control')
glXWaitForSbcOML = _link_function('glXWaitForSbcOML', c_int, [POINTER(Display), XID, c_int64, POINTER(c_int64), POINTER(c_int64), POINTER(c_int64)], 'GLX GLX_OML_sync_control')
glXWaitGL = _link_function('glXWaitGL', None, [], 'GLX 1.0')
glXWaitVideoSyncSGI = _link_function('glXWaitVideoSyncSGI', c_int, [c_int, c_int, POINTER(c_uint)], 'GLX GLX_SGI_video_sync')
glXWaitX = _link_function('glXWaitX', None, [], 'GLX 1.0')

__all__ = [
    'Bool',
    'GLbitfield',
    'GLboolean',
    'GLenum',
    'GLfloat',
    'GLint',
    'GLintptr',
    'GLsizei',
    'GLsizeiptr',
    'GLXContext',
    'GLXContextID',
    'GLXDrawable',
    'GLXFBConfig',
    'GLXFBConfigID',
    'GLXPbuffer',
    'GLXPixmap',
    'GLXWindow',
    'GLubyte',
    'GLuint',
    'GLvoid',
    '__GLXextFuncPtr',
    'GLX_EXTENSION_NAME',
    'GLX_PbufferClobber',
    'GLX_BufferSwapComplete',
    '__GLX_NUMBER_EVENTS',
    'GLX_BAD_SCREEN',
    'GLX_BAD_ATTRIBUTE',
    'GLX_NO_EXTENSION',
    'GLX_BAD_VISUAL',
    'GLX_BAD_CONTEXT',
    'GLX_BAD_VALUE',
    'GLX_BAD_ENUM',
    'GLX_USE_GL',
    'GLX_BUFFER_SIZE',
    'GLX_LEVEL',
    'GLX_RGBA',
    'GLX_DOUBLEBUFFER',
    'GLX_STEREO',
    'GLX_AUX_BUFFERS',
    'GLX_RED_SIZE',
    'GLX_GREEN_SIZE',
    'GLX_BLUE_SIZE',
    'GLX_ALPHA_SIZE',
    'GLX_DEPTH_SIZE',
    'GLX_STENCIL_SIZE',
    'GLX_ACCUM_RED_SIZE',
    'GLX_ACCUM_GREEN_SIZE',
    'GLX_ACCUM_BLUE_SIZE',
    'GLX_ACCUM_ALPHA_SIZE',
    'GLX_VENDOR',
    'GLX_VERSION',
    'GLX_EXTENSIONS',
    'GLX_WINDOW_BIT',
    'GLX_PIXMAP_BIT',
    'GLX_PBUFFER_BIT',
    'GLX_RGBA_BIT',
    'GLX_COLOR_INDEX_BIT',
    'GLX_PBUFFER_CLOBBER_MASK',
    'GLX_FRONT_LEFT_BUFFER_BIT',
    'GLX_FRONT_RIGHT_BUFFER_BIT',
    'GLX_BACK_LEFT_BUFFER_BIT',
    'GLX_BACK_RIGHT_BUFFER_BIT',
    'GLX_AUX_BUFFERS_BIT',
    'GLX_DEPTH_BUFFER_BIT',
    'GLX_STENCIL_BUFFER_BIT',
    'GLX_ACCUM_BUFFER_BIT',
    'GLX_CONFIG_CAVEAT',
    'GLX_X_VISUAL_TYPE',
    'GLX_TRANSPARENT_TYPE',
    'GLX_TRANSPARENT_INDEX_VALUE',
    'GLX_TRANSPARENT_RED_VALUE',
    'GLX_TRANSPARENT_GREEN_VALUE',
    'GLX_TRANSPARENT_BLUE_VALUE',
    'GLX_TRANSPARENT_ALPHA_VALUE',
    'GLX_DONT_CARE',
    'GLX_NONE',
    'GLX_SLOW_CONFIG',
    'GLX_TRUE_COLOR',
    'GLX_DIRECT_COLOR',
    'GLX_PSEUDO_COLOR',
    'GLX_STATIC_COLOR',
    'GLX_GRAY_SCALE',
    'GLX_STATIC_GRAY',
    'GLX_TRANSPARENT_RGB',
    'GLX_TRANSPARENT_INDEX',
    'GLX_VISUAL_ID',
    'GLX_SCREEN',
    'GLX_NON_CONFORMANT_CONFIG',
    'GLX_DRAWABLE_TYPE',
    'GLX_RENDER_TYPE',
    'GLX_X_RENDERABLE',
    'GLX_FBCONFIG_ID',
    'GLX_RGBA_TYPE',
    'GLX_COLOR_INDEX_TYPE',
    'GLX_MAX_PBUFFER_WIDTH',
    'GLX_MAX_PBUFFER_HEIGHT',
    'GLX_MAX_PBUFFER_PIXELS',
    'GLX_PRESERVED_CONTENTS',
    'GLX_LARGEST_PBUFFER',
    'GLX_WIDTH',
    'GLX_HEIGHT',
    'GLX_EVENT_MASK',
    'GLX_DAMAGED',
    'GLX_SAVED',
    'GLX_WINDOW',
    'GLX_PBUFFER',
    'GLX_PBUFFER_HEIGHT',
    'GLX_PBUFFER_WIDTH',
    'GLX_SAMPLE_BUFFERS',
    'GLX_SAMPLES',
    'GLX_CONTEXT_DEBUG_BIT_ARB',
    'GLX_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB',
    'GLX_CONTEXT_MAJOR_VERSION_ARB',
    'GLX_CONTEXT_MINOR_VERSION_ARB',
    'GLX_CONTEXT_FLAGS_ARB',
    'GLX_CONTEXT_CORE_PROFILE_BIT_ARB',
    'GLX_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB',
    'GLX_CONTEXT_PROFILE_MASK_ARB',
    'GLX_CONTEXT_ES2_PROFILE_BIT_EXT',
    'GLX_CONTEXT_ROBUST_ACCESS_BIT_ARB',
    'GLX_LOSE_CONTEXT_ON_RESET_ARB',
    'GLX_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB',
    'GLX_NO_RESET_NOTIFICATION_ARB',
    'GLX_RGBA_FLOAT_TYPE_ARB',
    'GLX_RGBA_FLOAT_BIT_ARB',
    'GLX_SWAP_INTERVAL_EXT',
    'GLX_MAX_SWAP_INTERVAL_EXT',
    'GLX_LATE_SWAPS_TEAR_EXT',
    'GLX_SHARE_CONTEXT_EXT',
    'GLX_VISUAL_ID_EXT',
    'GLX_SCREEN_EXT',
    'GLX_RENDERER_VENDOR_ID_MESA',
    'GLX_RENDERER_DEVICE_ID_MESA',
    'GLX_RENDERER_VERSION_MESA',
    'GLX_RENDERER_ACCELERATED_MESA',
    'GLX_RENDERER_VIDEO_MEMORY_MESA',
    'GLX_RENDERER_UNIFIED_MEMORY_ARCHITECTURE_MESA',
    'GLX_RENDERER_PREFERRED_PROFILE_MESA',
    'GLX_RENDERER_OPENGL_CORE_PROFILE_VERSION_MESA',
    'GLX_RENDERER_OPENGL_COMPATIBILITY_PROFILE_VERSION_MESA',
    'GLX_RENDERER_OPENGL_ES_PROFILE_VERSION_MESA',
    'GLX_RENDERER_OPENGL_ES2_PROFILE_VERSION_MESA',
    'GLX_CONTEXT_MULTIGPU_ATTRIB_NV',
    'GLX_CONTEXT_MULTIGPU_ATTRIB_SINGLE_NV',
    'GLX_CONTEXT_MULTIGPU_ATTRIB_AFR_NV',
    'GLX_CONTEXT_MULTIGPU_ATTRIB_MULTICAST_NV',
    'GLX_CONTEXT_MULTIGPU_ATTRIB_MULTI_DISPLAY_MULTICAST_NV',
    'glXBindSwapBarrierNV',
    'glXChooseFBConfig',
    'glXChooseVisual',
    'glXCopyContext',
    'glXCreateContext',
    'glXCreateContextAttribsARB',
    'glXCreateGLXPixmap',
    'glXCreateNewContext',
    'glXCreatePbuffer',
    'glXCreatePixmap',
    'glXCreateWindow',
    'glXDestroyContext',
    'glXDestroyGLXPixmap',
    'glXDestroyPbuffer',
    'glXDestroyPixmap',
    'glXDestroyWindow',
    'glXFreeContextEXT',
    'glXGetClientString',
    'glXGetConfig',
    'glXGetContextIDEXT',
    'glXGetCurrentContext',
    'glXGetCurrentDisplay',
    'glXGetCurrentDisplayEXT',
    'glXGetCurrentDrawable',
    'glXGetCurrentReadDrawable',
    'glXGetFBConfigAttrib',
    'glXGetFBConfigs',
    'glXGetMscRateOML',
    'glXGetProcAddress',
    'glXGetSelectedEvent',
    'glXGetSwapIntervalMESA',
    'glXGetSyncValuesOML',
    'glXGetVideoSyncSGI',
    'glXGetVisualFromFBConfig',
    'glXImportContextEXT',
    'glXIsDirect',
    'glXJoinSwapGroupNV',
    'glXMakeContextCurrent',
    'glXMakeCurrent',
    'glXQueryContext',
    'glXQueryContextInfoEXT',
    'glXQueryCurrentRendererIntegerMESA',
    'glXQueryCurrentRendererStringMESA',
    'glXQueryDrawable',
    'glXQueryExtension',
    'glXQueryExtensionsString',
    'glXQueryFrameCountNV',
    'glXQueryMaxSwapGroupsNV',
    'glXQueryRendererIntegerMESA',
    'glXQueryRendererStringMESA',
    'glXQueryServerString',
    'glXQuerySwapGroupNV',
    'glXQueryVersion',
    'glXResetFrameCountNV',
    'glXSelectEvent',
    'glXSwapBuffers',
    'glXSwapBuffersMscOML',
    'glXSwapIntervalEXT',
    'glXSwapIntervalMESA',
    'glXSwapIntervalSGI',
    'glXUseXFont',
    'glXWaitForMscOML',
    'glXWaitForSbcOML',
    'glXWaitGL',
    'glXWaitVideoSyncSGI',
    'glXWaitX',
]
