import os
import wave
import unittest

import pytest

from io import BytesIO

from pyglet.media.synthesis import *


local_dir = os.path.dirname(__file__)
test_data_path = os.path.abspath(os.path.join(local_dir, '..', '..', 'data'))
del local_dir


def get_test_data_file(*file_parts):
    """Get a file from the test data directory in an OS independent way.

    Supply relative file name as you would in os.path.join().
    """
    return os.path.join(test_data_path, *file_parts)


classes = [Silence, WhiteNoise, Sine, Triangle, Sawtooth, Square]
sample_rates = [44800, 11025]


@pytest.mark.parametrize('source_class', classes)
@pytest.mark.parametrize('sample_rate', sample_rates)
def test_instantiation(source_class, sample_rate):
    source = source_class(duration=1, sample_rate=sample_rate)


@pytest.mark.parametrize('source_class', classes)
@pytest.mark.parametrize('sample_rate', sample_rates)
def test_total_duration(source_class, sample_rate):
    source = source_class(duration=1)                       # One second of audio...
    expected_bytes = source.audio_format.bytes_per_second   # should match this.
    audio_data = source.get_audio_data(expected_bytes + 100)

    assert audio_data.length == pytest.approx(expected_bytes)
    assert audio_data.duration == pytest.approx(1.0)
    assert len(audio_data.data) == pytest.approx(expected_bytes)

    # Should now be out of data
    last_data = source.get_audio_data(100)
    assert last_data is None


@pytest.mark.parametrize('source_class', classes)
@pytest.mark.parametrize('sample_rate', sample_rates)
def test_generated_bytes(source_class, sample_rate):
    if source_class == WhiteNoise:
        return

    source = source_class(duration=1, sample_rate=sample_rate)
    source_name = source_class.__name__.lower()
    filename = "synthesis_{0}_{1}_{2}_1ch.wav".format(source_name, 16, sample_rate)

    with wave.open(get_test_data_file('media', filename)) as f:
        loaded_bytes = f.readframes(-1)
        generated_data = source.get_audio_data(source._max_offset)
        bytes_buffer = BytesIO(generated_data.data).getvalue()
        # Compare a small chunk, to avoid hanging on mismatch:
        assert bytes_buffer[:1000] == loaded_bytes[:1000], "Generated bytes do not match sample wave file."


@pytest.mark.parametrize('attack', [0, 0.05, 0.2])
@pytest.mark.parametrize('decay', [0, 0.05, 0.2])
@pytest.mark.parametrize('release', [0, 0.05, 0.2])
def test_adsr_zero_sample_stages(attack, decay, release):
    envelope = ADSREnvelope(attack, decay, release, sustain_amplitude=0.5)
    generator = envelope.get_generator(sample_rate=10, duration=1)

    # At 10 Hz, 0 and 0.05 seconds produce no samples, and 0.2 produces two.
    attack_samples = [0.5, 1.0] if attack == 0.2 else []
    decay_samples = [0.75, 0.5] if decay == 0.2 else []
    release_samples = [0.25, 0.0] if release == 0.2 else []
    sustain_samples = [0.5] * (10 - len(attack_samples) - len(decay_samples) - len(release_samples))
    expected = attack_samples + decay_samples + sustain_samples + release_samples

    assert [next(generator) for _ in range(10)] == pytest.approx(expected)
    assert [next(generator) for _ in range(3)] == [0, 0, 0]


def test_synthesis_with_zero_length_adsr_stages():
    source = Sine(duration=1, frequency=1, sample_rate=10, envelope=ADSREnvelope(0.2, 0, 0))
    audio_data = source.get_audio_data(20)

    assert audio_data.length == 20
    assert len(audio_data.data) == 20
    assert audio_data.duration == pytest.approx(1)
    assert source.get_audio_data(20) is None
